import React, { useMemo, useRef } from "react";
import { Alert, Button, Card, Field, ResponsiveActions, StatusBadge } from "./ui/components.jsx";
import { DELIVERY_MODES, EMPTY_MISSION_TEMPLATE, SAFE_MISSION_TEMPLATE, SOURCE_KINDS, splitMissionLines, validateMissionDraft } from "./mission-model.js";
import "./mission-builder.css";

const DELIVERY_LABELS = { "no-write": "No-write", "patch-only": "Patch only", "local-branch": "Local branch", "fork-first-pr": "Fork-first PR" };

function SourceRows({ value, onChange, busy }) {
  const rows = Array.isArray(value) ? value : [];
  const update = (index, patch) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  return <div className="mission-source-list"><div className="mission-list-heading"><strong>Local structured sources</strong><Button type="button" size="compact" onClick={() => onChange([...rows, { sourceKind: "local-note", ref: "" }])} disabled={busy}>Add source</Button></div>{rows.length === 0 ? <p>No local source is attached. The Mission will remain incomplete.</p> : rows.map((row, index) => <div className="mission-source-row" key={`${index}-${row.sourceKind}`}><select aria-label={`Source ${index + 1} kind`} value={row.sourceKind} onChange={(event) => update(index, { sourceKind: event.target.value })}>{SOURCE_KINDS.map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select><input aria-label={`Source ${index + 1} reference`} value={row.ref} placeholder="docs/product/brief.md" onChange={(event) => update(index, { ref: event.target.value })}/><Button type="button" size="compact" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))} disabled={busy}>Remove</Button></div>)}</div>;
}

export function MissionBuilder({ form, setForm, busy, onSubmit, onResume, operation, onCancel, followUpSourceHandoffRef = null }) {
  const summaryRef = useRef(null);
  const validation = useMemo(() => validateMissionDraft(form), [form]);
  const incompleteBlocked = validation.structurallyValid && !validation.complete && form.acknowledgeIncomplete !== true;
  const submit = (event) => {
    event.preventDefault();
    if (!validation.structurallyValid || incompleteBlocked) {
      summaryRef.current?.focus();
      requestAnimationFrame(() => document.querySelector('.mission-builder [aria-invalid="true"]')?.focus());
      return;
    }
    onSubmit(event, validation);
  };
  if (operation?.phase === "next-pending") return <Card className="mission-operation-card"><StatusBadge tone="warning">Mission created; next action pending</StatusBadge><h2>Resume first-flow creation</h2><p>The Mission and intake evidence already exist. Retry only next-action resolution.</p><ul>{[...(operation.artifactRefs ?? []), ...(operation.evidenceRefs ?? [])].map((ref) => <li key={ref}><code>{ref}</code></li>)}</ul>{operation.error ? <Alert tone="danger">{operation.error}</Alert> : null}<Button variant="primary" busy={busy} onClick={onResume}>Resolve next action</Button></Card>;
  return <form className="mission-builder aor-ui" aria-label="Guided Mission intake" noValidate onSubmit={submit}>
    <header><div><p className="mission-eyebrow">Mission intake</p><h1>{followUpSourceHandoffRef ? "Create follow-up Flow" : "Start a new Flow"}</h1><p>Define product acceptance and bounded execution before AOR creates durable evidence.</p></div><StatusBadge tone={validation.complete ? "success" : validation.structurallyValid ? "warning" : "danger"}>{validation.complete ? "Complete" : validation.structurallyValid ? "Incomplete" : "Invalid"}</StatusBadge></header>
    {(!validation.structurallyValid || incompleteBlocked) ? <div className="mission-error-summary" role="alert" tabIndex="-1" ref={summaryRef}><strong>{validation.structurallyValid ? "Acknowledge the incomplete Mission before preserving it." : "Correct the Mission fields before creating evidence."}</strong>{Object.values(validation.fieldErrors).length ? <ul>{Object.values(validation.fieldErrors).map((message) => <li key={message}>{message}</li>)}</ul> : null}{validation.missingFields.length ? <p>Missing evidence: {validation.missingFields.join(", ")}. Blocked stages: {validation.blockedStages.join(", ")}.</p> : null}</div> : null}
    <Card><div className="mission-grid"><Field label="Mission title" helper="Used as the human Flow identity." error={validation.fieldErrors.title}><input name="mission-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })}/></Field><Field label="Brief" helper="State the bounded outcome." error={validation.fieldErrors.brief}><textarea name="mission-brief" value={form.brief} onChange={(event) => setForm({ ...form, brief: event.target.value })}/></Field></div></Card>
    <Card><h2>Acceptance evidence</h2><div className="mission-grid"><Field label="Goals" helper="One goal per line."><textarea name="mission-goals" value={form.goals} onChange={(event) => setForm({ ...form, goals: event.target.value })}/></Field><Field label="Constraints" helper="One constraint per line."><textarea name="mission-constraints" value={form.constraints} onChange={(event) => setForm({ ...form, constraints: event.target.value })}/></Field><Field label="KPIs" helper="kpi-id:name:target[:measurement]" error={validation.fieldErrors.kpi}><textarea name="mission-kpi" value={form.kpi} onChange={(event) => setForm({ ...form, kpi: event.target.value })}/></Field><Field label="Definition of Done" helper="One check per line."><textarea name="mission-dod" value={form.dod} onChange={(event) => setForm({ ...form, dod: event.target.value })}/></Field></div><SourceRows value={form.sourceRefs} onChange={(sourceRefs) => setForm({ ...form, sourceRefs })} busy={busy}/>{validation.fieldErrors.sourceRefs ? <Alert tone="danger">{validation.fieldErrors.sourceRefs}</Alert> : null}</Card>
    <Card><h2>Bounded execution</h2><div className="mission-delivery-options" role="radiogroup" aria-label="Delivery mode">{DELIVERY_MODES.map((mode) => <button type="button" role="radio" aria-checked={form.deliveryMode === mode} className="mission-delivery-option" data-selected={form.deliveryMode === mode} key={mode} onClick={() => setForm({ ...form, deliveryMode: mode })}><strong>{DELIVERY_LABELS[mode]}</strong><span>{mode === "no-write" ? "Runtime evidence only; no target-source or upstream writes." : "Requires downstream policy and review gates."}</span></button>)}</div><div className="mission-grid"><Field label="Allowed paths" helper="Project-relative canonical globs. Empty means no declared write scope." error={validation.fieldErrors.allowedPaths}><input name="mission-allowed-paths" value={form.allowedPaths} placeholder="apps/web/**" onChange={(event) => setForm({ ...form, allowedPaths: event.target.value })}/></Field><Field label="Forbidden paths" helper="Project-relative paths that remain out of scope." error={validation.fieldErrors.forbiddenPaths}><input name="mission-forbidden-paths" value={form.forbiddenPaths} placeholder="secrets/**" onChange={(event) => setForm({ ...form, forbiddenPaths: event.target.value })}/></Field></div></Card>
    {!validation.complete && validation.structurallyValid ? <label className="mission-incomplete-ack"><input type="checkbox" checked={form.acknowledgeIncomplete === true} onChange={(event) => setForm({ ...form, acknowledgeIncomplete: event.target.checked })}/><span>Preserve this incomplete Mission. I understand that {validation.blockedStages.join(", ")} will remain blocked.</span></label> : null}
    {followUpSourceHandoffRef ? <p className="mission-lineage">Follow-up source: <code>{followUpSourceHandoffRef}</code>. The completed source Flow remains read-only.</p> : null}
    <section className="mission-preview" aria-label="Mission completeness and safety preview"><div><span>Evidence groups</span><strong>{5 - validation.missingFields.length}/5 complete</strong></div><div><span>Delivery</span><strong>{DELIVERY_LABELS[form.deliveryMode] ?? "Invalid"}</strong></div><div><span>Scope</span><strong>{splitMissionLines(form.allowedPaths).length || 0} allowed / {splitMissionLines(form.forbiddenPaths).length || 0} forbidden</strong></div></section>
    <ResponsiveActions><Button variant="primary" type="submit" busy={busy}>{followUpSourceHandoffRef ? "Create follow-up Mission evidence" : "Create Mission evidence"}</Button><Button type="button" onClick={() => setForm({ ...SAFE_MISSION_TEMPLATE })} disabled={busy}>Load safe walkthrough</Button><Button type="button" onClick={() => setForm({ ...EMPTY_MISSION_TEMPLATE, sourceRefs: [] })} disabled={busy}>Clear form</Button>{onCancel ? <Button type="button" onClick={onCancel} disabled={busy}>Cancel</Button> : null}</ResponsiveActions>
  </form>;
}

export function MissionDurableSummary({ flow }) {
  if (!flow?.intake_packet_ref && !flow?.latest_next_action_report_ref) return null;
  return <Alert tone="success"><strong>Mission evidence is durable.</strong><span> Reload and reconnect preserve this Flow from runtime evidence.</span><ul>{[flow.intake_packet_ref, flow.latest_next_action_report_ref].filter(Boolean).map((ref) => <li key={ref}><code>{ref}</code></li>)}</ul></Alert>;
}
