const STEP_CLASS_VALUES = ["artifact", "planner", "runner", "repair", "eval", "harness"];
const ROUTE_STEP_VALUES = [
  "discovery",
  "research",
  "spec",
  "planning",
  "implement",
  "review",
  "qa",
  "repair",
  "eval",
  "harness",
];
const PROMOTION_CHANNEL_VALUES = ["draft", "candidate", "stable", "frozen", "demoted"];
const INCIDENT_SEVERITY_VALUES = ["low", "medium", "high", "critical"];
const INCIDENT_STATUS_VALUES = ["open", "recertify", "hold", "re-enabled", "closed"];
const INCIDENT_BACKFILL_PROPOSAL_STATE_VALUES = ["proposed", "approved", "rejected"];
const REVIEW_DECISION_VALUES = ["approve", "hold", "request-repair"];
const PLANNER_METRICS_STATUS_VALUES = ["no-data", "partial", "ready"];
const MULTIREPO_COORDINATION_STATUS_VALUES = ["ready", "blocked", "released"];
const COMPILER_REVISION_LIFECYCLE_VALUES = ["draft", "candidate", "stable", "frozen", "demoted", "blocked"];
const COMPILER_REVISION_STATUS_VALUES = ["ready", "blocked"];
const DELIVERY_MODE_VALUES = ["no-write", "patch-only", "local-branch", "fork-first-pr"];
const DELIVERY_PLAN_STATUS_VALUES = ["ready", "blocked"];
export const LIVE_E2E_OBSERVATION_STATUS_VALUES = ["pass", "warn", "not_pass"];
const LIVE_E2E_SCENARIO_VALUES = ["regress", "release", "repair", "governance"];
const LIVE_E2E_PROVIDER_VARIANT_VALUES = ["openai-primary", "anthropic-primary", "open-code-primary"];
export const INTAKE_SOURCE_KIND_VALUES = ["local-issue", "local-prd", "local-rfc", "local-note", "local-mail"];
const LIVE_RUN_EVENT_TYPE_VALUES = [
  "run.started",
  "step.updated",
  "evidence.linked",
  "warning.raised",
  "run.terminal",
];
export const EXTERNAL_REFERENCE_PREFIXES = [
  "evidence://",
  "schema://",
  "approval://",
  "incident://",
  "review://",
  "redact://",
  "validate.",
  "retry.",
  "repair.",
];

/** @type {ReadonlyArray<import("./index.d.ts").ContractFamilyIndexEntry>} */
export const CONTRACT_FAMILY_INDEX = Object.freeze([
  {
    family: "project-profile",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/project-profile.md",
    exampleGlob: "examples/project*.aor.yaml",
    status: "implemented",
    requiredFields: [
      "project_id",
      "display_name",
      "repo_topology",
      "repos",
      "allowed_providers",
      "allowed_adapters",
      "registry_roots",
      "default_route_profiles",
      "default_step_policies",
      "default_wrapper_profiles",
      "default_prompt_bundles",
      "default_context_bundles",
      "default_skill_profiles",
      "skill_overrides",
      "budget_policy",
      "approval_policy",
      "security_policy",
      "runtime_defaults",
      "writeback_policy",
    ],
    fieldTypes: {
      project_id: "string",
      display_name: "string",
      repo_topology: "string",
      repos: "array",
      allowed_providers: "array",
      allowed_adapters: "array",
      registry_roots: "object",
      default_route_profiles: "object",
      default_step_policies: "object",
      default_wrapper_profiles: "object",
      default_prompt_bundles: "object",
      default_context_bundles: "object",
      default_skill_profiles: "object",
      skill_overrides: "object",
      budget_policy: "object",
      approval_policy: "object",
      security_policy: "object",
      runtime_defaults: "object",
      writeback_policy: "object",
    },
    enumChecks: [],
  },
  {
    family: "project-analysis-report",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/project-analysis-report.md",
    exampleGlob: "examples/project-analysis-report.sample.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "project_id",
      "version",
      "generated_from",
      "repo_facts",
      "toolchain_facts",
      "command_catalog",
      "route_resolution",
      "asset_resolution",
      "policy_resolution",
      "evaluation_registry",
      "discovery_research",
      "verification_plan",
      "status",
    ],
    fieldTypes: {
      report_id: "string",
      project_id: "string",
      version: "number",
      generated_from: "object",
      repo_facts: "object",
      toolchain_facts: "object",
      command_catalog: "object",
      route_resolution: "object",
      asset_resolution: "object",
      policy_resolution: "object",
      evaluation_registry: "object",
      discovery_research: "object",
      verification_plan: "object",
      status: "string",
    },
    enumChecks: [],
  },
  {
    family: "discovery-research-report",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/discovery-research-report.md",
    exampleGlob: "examples/reports/discovery-research-report*.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "project_id",
      "version",
      "generated_from",
      "repository_facts",
      "context_assets",
      "research_inputs",
      "open_questions",
      "adr_ready_recommendations",
      "completeness",
      "status",
    ],
    fieldTypes: {
      report_id: "string",
      project_id: "string",
      version: "number",
      generated_from: "object",
      repository_facts: "object",
      context_assets: "object",
      research_inputs: "object",
      open_questions: "array",
      adr_ready_recommendations: "array",
      completeness: "object",
      status: "string",
    },
    enumChecks: [{ field: "status", allowedValues: ["adr-ready", "incomplete"] }],
  },
  {
    family: "artifact-packet",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/artifact-packet.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: ["packet_id", "project_id", "packet_type", "version", "status", "summary", "body_ref"],
    fieldTypes: {
      packet_id: "string",
      project_id: "string",
      packet_type: "string",
      version: "number",
      status: "string",
      summary: "string",
      body_ref: "string",
    },
    enumChecks: [],
  },
  {
    family: "intake-request-body",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/intake-request-body.md",
    exampleGlob: "examples/packets/intake-request-body*.yaml",
    status: "implemented",
    requiredFields: [
      "generated_from",
      "project_identity",
      "mission_traceability",
      "product_intake",
      "product_intake_completeness",
      "feature_request",
      "evidence_roots",
    ],
    fieldTypes: {
      generated_from: "object",
      project_identity: "object",
      mission_traceability: "object",
      product_intake: "object",
      product_intake_completeness: "object",
      feature_request: "object",
      evidence_roots: "object",
    },
    enumChecks: [],
  },
  {
    family: "wave-ticket",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/wave-ticket.md",
    exampleGlob: "examples/packets/wave-ticket-*.yaml",
    status: "implemented",
    requiredFields: [
      "ticket_id",
      "project_id",
      "objective",
      "scope",
      "dependencies",
      "risk_tier",
      "status",
      "approved_input_ref",
    ],
    fieldTypes: {
      ticket_id: "string",
      project_id: "string",
      objective: "string",
      scope: "object",
      dependencies: "array",
      risk_tier: "string",
      status: "string",
      approved_input_ref: "string",
    },
    enumChecks: [],
  },
  {
    family: "handoff-packet",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/handoff-packet.md",
    exampleGlob: "examples/packets/handoff-*.yaml",
    status: "implemented",
    requiredFields: [
      "packet_id",
      "project_id",
      "ticket_id",
      "version",
      "status",
      "risk_tier",
      "approved_objective",
      "repo_scopes",
      "allowed_paths",
      "allowed_commands",
      "verification_plan",
      "scope_constraints",
      "command_policy",
      "writeback_mode",
      "approval_state",
    ],
    fieldTypes: {
      packet_id: "string",
      project_id: "string",
      ticket_id: "string",
      version: "number",
      status: "string",
      risk_tier: "string",
      approved_objective: "string",
      repo_scopes: "array",
      allowed_paths: "array",
      allowed_commands: "array",
      verification_plan: "object",
      scope_constraints: "object",
      command_policy: "object",
      writeback_mode: "string",
      approval_state: "object",
    },
    enumChecks: [],
  },
  {
    family: "release-packet",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/release-packet.md",
    exampleGlob: "examples/packets/release-*.yaml",
    status: "implemented",
    requiredFields: [
      "packet_id",
      "project_id",
      "ticket_id",
      "run_refs",
      "change_summary",
      "verification_refs",
      "delivery_manifest_ref",
      "evidence_lineage",
      "status",
      "created_at",
    ],
    fieldTypes: {
      packet_id: "string",
      project_id: "string",
      ticket_id: "string",
      run_refs: "array",
      change_summary: "string",
      verification_refs: "array",
      delivery_manifest_ref: "string",
      evidence_lineage: "object",
      status: "string",
      created_at: "string",
    },
    enumChecks: [],
  },
  {
    family: "delivery-plan",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/delivery-plan.md",
    exampleGlob: "examples/packets/delivery-plan-*.yaml",
    status: "implemented",
    requiredFields: [
      "plan_id",
      "project_id",
      "run_id",
      "step_class",
      "delivery_mode",
      "mode_source",
      "preconditions",
      "writeback_allowed",
      "blocking_reasons",
      "status",
      "evidence_refs",
      "created_at",
    ],
    fieldTypes: {
      plan_id: "string",
      project_id: "string",
      run_id: "string",
      step_class: "string",
      delivery_mode: "string",
      mode_source: "object",
      preconditions: "object",
      writeback_allowed: "boolean",
      blocking_reasons: "array",
      status: "string",
      evidence_refs: "array",
      created_at: "string",
    },
    enumChecks: [
      { field: "delivery_mode", allowedValues: DELIVERY_MODE_VALUES },
      { field: "status", allowedValues: DELIVERY_PLAN_STATUS_VALUES },
    ],
  },
  {
    family: "delivery-manifest",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/delivery-manifest.md",
    exampleGlob: "examples/delivery-manifest*.yaml",
    status: "implemented",
    requiredFields: [
      "manifest_id",
      "project_id",
      "ticket_id",
      "run_refs",
      "step_ref",
      "delivery_mode",
      "writeback_policy",
      "repo_deliveries",
      "verification_refs",
      "approval_context",
      "evidence_root",
      "source_refs",
      "status",
      "created_at",
    ],
    fieldTypes: {
      manifest_id: "string",
      project_id: "string",
      ticket_id: "string",
      run_refs: "array",
      step_ref: "string",
      delivery_mode: "string",
      writeback_policy: "object",
      repo_deliveries: "array",
      verification_refs: "array",
      approval_context: "object",
      evidence_root: "string",
      source_refs: "object",
      status: "string",
      created_at: "string",
    },
    enumChecks: [],
  },
  {
    family: "incident-report",
    familyGroup: "core-packets-and-profiles",
    sourceContract: "docs/contracts/incident-report.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: ["incident_id", "project_id", "severity", "summary", "linked_run_refs", "linked_asset_refs", "status"],
    fieldTypes: {
      incident_id: "string",
      project_id: "string",
      severity: "string",
      summary: "string",
      linked_run_refs: "array",
      linked_asset_refs: "array",
      status: "string",
    },
    enumChecks: [
      { field: "severity", allowedValues: INCIDENT_SEVERITY_VALUES },
      { field: "status", allowedValues: INCIDENT_STATUS_VALUES },
    ],
  },
  {
    family: "incident-backfill-proposal",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/incident-backfill-proposal.md",
    exampleGlob: "examples/reports/incident-backfill-proposal*.yaml",
    status: "implemented",
    requiredFields: [
      "proposal_id",
      "project_id",
      "proposal_state",
      "source_artifacts",
      "target",
      "proposed_cases",
      "mutation_policy",
      "evidence_refs",
      "created_at",
    ],
    fieldTypes: {
      proposal_id: "string",
      project_id: "string",
      proposal_state: "string",
      source_artifacts: "object",
      target: "object",
      proposed_cases: "array",
      mutation_policy: "object",
      evidence_refs: "array",
      created_at: "string",
    },
    enumChecks: [{ field: "proposal_state", allowedValues: INCIDENT_BACKFILL_PROPOSAL_STATE_VALUES }],
  },
  {
    family: "step-result",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/step-result.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: ["step_result_id", "run_id", "step_id", "step_class", "status", "summary", "evidence_refs"],
    fieldTypes: {
      step_result_id: "string",
      run_id: "string",
      step_id: "string",
      step_class: "string",
      status: "string",
      summary: "string",
      evidence_refs: "array",
    },
    enumChecks: [{ field: "step_class", allowedValues: STEP_CLASS_VALUES }],
  },
  {
    family: "validation-report",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/validation-report.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: ["report_id", "subject_ref", "validators", "status", "evidence_refs"],
    fieldTypes: {
      report_id: "string",
      subject_ref: "string",
      validators: "array",
      status: "string",
      evidence_refs: "array",
    },
    enumChecks: [],
  },
  {
    family: "evaluation-report",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/evaluation-report.md",
    exampleGlob: "examples/eval/report-*.sample.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "subject_ref",
      "subject_type",
      "subject_fingerprint",
      "suite_ref",
      "dataset_ref",
      "scorer_metadata",
      "grader_results",
      "summary_metrics",
      "status",
      "evidence_refs",
    ],
    fieldTypes: {
      report_id: "string",
      subject_ref: "string",
      subject_type: "string",
      subject_fingerprint: "string",
      suite_ref: "string",
      dataset_ref: "string",
      scorer_metadata: "array",
      grader_results: "object",
      summary_metrics: "object",
      status: "string",
      evidence_refs: "array",
    },
    enumChecks: [],
  },
  {
    family: "review-report",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/review-report.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: [
      "review_report_id",
      "project_id",
      "run_id",
      "generated_at",
      "overall_status",
      "review_recommendation",
      "feature_traceability",
      "discovery_quality",
      "artifact_quality",
      "code_quality",
      "feature_size_fit",
      "provider_traceability",
      "findings",
      "evidence_refs",
    ],
    fieldTypes: {
      review_report_id: "string",
      project_id: "string",
      run_id: "string",
      generated_at: "string",
      overall_status: "string",
      review_recommendation: "string",
      feature_traceability: "object",
      discovery_quality: "object",
      artifact_quality: "object",
      code_quality: "object",
      feature_size_fit: "object",
      provider_traceability: "object",
      findings: "array",
      evidence_refs: "array",
    },
    enumChecks: [
      { field: "overall_status", allowedValues: ["pass", "warn", "fail"] },
      { field: "review_recommendation", allowedValues: ["proceed", "repair", "required-human-review"] },
    ],
  },
  {
    family: "review-decision",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/review-decision.md",
    exampleGlob: "examples/reports/review-decision*.yaml",
    status: "implemented",
    requiredFields: [
      "decision_id",
      "project_id",
      "run_id",
      "decision",
      "decider_ref",
      "reason",
      "review_report_ref",
      "runtime_harness_report_ref",
      "delivery_manifest_refs",
      "learning_handoff_refs",
      "decision_basis",
      "delivery_gate",
      "evidence_refs",
      "decided_at",
    ],
    fieldTypes: {
      decision_id: "string",
      project_id: "string",
      run_id: "string",
      decision: "string",
      decider_ref: "string",
      reason: "string",
      review_report_ref: "string",
      runtime_harness_report_ref: "string",
      delivery_manifest_refs: "array",
      learning_handoff_refs: "array",
      decision_basis: "object",
      delivery_gate: "object",
      evidence_refs: "array",
      decided_at: "string",
    },
    enumChecks: [{ field: "decision", allowedValues: REVIEW_DECISION_VALUES }],
  },
  {
    family: "runtime-harness-report",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/runtime-harness-report.md",
    exampleGlob: "examples/reports/runtime-harness-report*.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "project_id",
      "run_id",
      "generated_at",
      "mission_type",
      "strictness_profile",
      "overall_decision",
      "step_decisions",
      "run_findings",
      "recommendations",
      "impacted_asset_refs",
      "promotion_recommendations",
      "unresolved_gaps",
      "evidence_refs",
    ],
    fieldTypes: {
      report_id: "string",
      project_id: "string",
      run_id: "string",
      generated_at: "string",
      mission_type: "string",
      strictness_profile: "string",
      overall_decision: "string",
      step_decisions: "array",
      run_findings: "array",
      recommendations: "array",
      impacted_asset_refs: "array",
      promotion_recommendations: "array",
      unresolved_gaps: "array",
      evidence_refs: "array",
    },
    enumChecks: [
      { field: "overall_decision", allowedValues: ["pass", "retry", "repair", "escalate", "block", "fail"] },
      {
        field: "mission_type",
        allowedValues: ["code-changing", "docs-only", "no-write-rehearsal", "release", "asset-certification", "unknown"],
      },
    ],
  },
  {
    family: "live-e2e-observation-report",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/live-e2e-observation-report.md",
    exampleGlob: "examples/reports/live-e2e-observation-report*.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "run_id",
      "profile_id",
      "flow_range",
      "overall_status",
      "step_matrix",
      "artifact_quality_matrix",
      "code_quality_after_delivery",
      "continuation_decisions",
      "evidence_refs",
    ],
    fieldTypes: {
      report_id: "string",
      run_id: "string",
      profile_id: "string",
      flow_range: "object",
      overall_status: "string",
      step_matrix: "array",
      artifact_quality_matrix: "array",
      code_quality_after_delivery: "object",
      continuation_decisions: "array",
      evidence_refs: "array",
    },
    enumChecks: [{ field: "overall_status", allowedValues: LIVE_E2E_OBSERVATION_STATUS_VALUES }],
  },
  {
    family: "multirepo-coordination-status",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/multirepo-coordination-status.md",
    exampleGlob: "examples/reports/multirepo-coordination-status*.yaml",
    status: "implemented",
    requiredFields: [
      "status_id",
      "project_id",
      "run_id",
      "version",
      "generated_from",
      "lock_scope",
      "lock_state",
      "cross_repo_validation",
      "delivery_evidence",
      "status",
      "blocking_reasons",
      "evidence_refs",
      "created_at",
    ],
    fieldTypes: {
      status_id: "string",
      project_id: "string",
      run_id: "string",
      version: "number",
      generated_from: "object",
      lock_scope: "object",
      lock_state: "object",
      cross_repo_validation: "object",
      delivery_evidence: "object",
      status: "string",
      blocking_reasons: "array",
      evidence_refs: "array",
      created_at: "string",
    },
    enumChecks: [{ field: "status", allowedValues: MULTIREPO_COORDINATION_STATUS_VALUES }],
  },
  {
    family: "dataset",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/dataset.md",
    exampleGlob: "examples/eval/dataset-*.yaml",
    status: "implemented",
    requiredFields: ["dataset_id", "version", "subject_type", "provenance", "cases"],
    fieldTypes: {
      dataset_id: "string",
      version: "string",
      subject_type: "string",
      provenance: "object",
      cases: "array",
    },
    enumChecks: [],
  },
  {
    family: "evaluation-suite",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/evaluation-suite.md",
    exampleGlob: "examples/eval/suite-*.yaml",
    status: "implemented",
    requiredFields: ["suite_id", "version", "subject_type", "dataset_ref", "graders", "thresholds"],
    fieldTypes: {
      suite_id: "string",
      version: "number",
      subject_type: "string",
      dataset_ref: "string",
      graders: "array",
      thresholds: "object",
    },
    enumChecks: [],
  },
  {
    family: "promotion-decision",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/promotion-decision.md",
    exampleGlob: "examples/packets/promotion-decision-*.yaml",
    status: "implemented",
    requiredFields: [
      "decision_id",
      "subject_ref",
      "from_channel",
      "to_channel",
      "evidence_refs",
      "evidence_summary",
      "status",
    ],
    fieldTypes: {
      decision_id: "string",
      subject_ref: "string",
      from_channel: "string",
      to_channel: "string",
      evidence_refs: "array",
      evidence_summary: "object",
      status: "string",
    },
    enumChecks: [
      { field: "from_channel", allowedValues: PROMOTION_CHANNEL_VALUES },
      { field: "to_channel", allowedValues: PROMOTION_CHANNEL_VALUES },
      { field: "status", allowedValues: ["pass", "hold", "fail"] },
    ],
  },
  {
    family: "compiled-context-artifact",
    familyGroup: "execution-and-quality",
    sourceContract: "docs/contracts/compiled-context-artifact.md",
    exampleGlob: "examples/context/compiled/*.yaml",
    status: "implemented",
    requiredFields: [
      "compiled_context_id",
      "version",
      "step",
      "prompt_bundle_ref",
      "context_bundle_refs",
      "context_doc_refs",
      "context_rule_refs",
      "context_skill_refs",
      "packet_refs",
      "hashes",
      "provenance",
    ],
    fieldTypes: {
      compiled_context_id: "string",
      version: "number",
      step: "string",
      prompt_bundle_ref: "string",
      context_bundle_refs: "array",
      context_doc_refs: "array",
      context_rule_refs: "array",
      context_skill_refs: "array",
      packet_refs: "array",
      hashes: "object",
      provenance: "object",
    },
    enumChecks: [],
  },
  {
    family: "provider-route-profile",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/provider-route-profile.md",
    exampleGlob: "examples/routes/*.yaml",
    status: "implemented",
    requiredFields: ["route_id", "step", "route_class", "risk_tier", "primary"],
    forbiddenFields: ["wrapper_profile_ref"],
    fieldTypes: {
      route_id: "string",
      step: "string",
      route_class: "string",
      risk_tier: "string",
      primary: "object",
    },
    enumChecks: [],
  },
  {
    family: "wrapper-profile",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/wrapper-profile.md",
    exampleGlob: "examples/wrappers/*.yaml",
    status: "implemented",
    requiredFields: ["wrapper_id", "version", "step_class", "tool_policy", "command_policy"],
    forbiddenFields: ["prompt_bundle_ref", "session_bootstrap"],
    fieldTypes: {
      wrapper_id: "string",
      version: "number",
      step_class: "string",
      tool_policy: "object",
      command_policy: "object",
    },
    enumChecks: [{ field: "step_class", allowedValues: STEP_CLASS_VALUES }],
  },
  {
    family: "prompt-bundle",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/prompt-bundle.md",
    exampleGlob: "examples/prompts/*.yaml",
    status: "implemented",
    requiredFields: ["prompt_bundle_id", "version", "step_class", "objective", "instructions", "required_inputs"],
    fieldTypes: {
      prompt_bundle_id: "string",
      version: "number",
      step_class: "string",
      objective: "string",
      instructions: "object",
      required_inputs: "object",
    },
    enumChecks: [{ field: "step_class", allowedValues: STEP_CLASS_VALUES }],
  },
  {
    family: "context-doc",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/context-doc.md",
    exampleGlob: "examples/context/docs/*.yaml",
    status: "implemented",
    requiredFields: ["context_doc_id", "version", "title", "metadata", "source", "applies_to"],
    fieldTypes: {
      context_doc_id: "string",
      version: "number",
      title: "string",
      metadata: "object",
      source: "object",
      applies_to: "object",
    },
    enumChecks: [],
  },
  {
    family: "context-rule",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/context-rule.md",
    exampleGlob: "examples/context/rules/*.yaml",
    status: "implemented",
    requiredFields: ["context_rule_id", "version", "title", "metadata", "instruction", "source_refs", "applies_to"],
    fieldTypes: {
      context_rule_id: "string",
      version: "number",
      title: "string",
      metadata: "object",
      instruction: "string",
      source_refs: "array",
      applies_to: "object",
    },
    enumChecks: [],
  },
  {
    family: "context-skill",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/context-skill.md",
    exampleGlob: "examples/context/skills/*.yaml",
    status: "implemented",
    requiredFields: [
      "context_skill_id",
      "version",
      "title",
      "metadata",
      "objective",
      "workflow",
      "source_refs",
      "applies_to",
    ],
    fieldTypes: {
      context_skill_id: "string",
      version: "number",
      title: "string",
      metadata: "object",
      objective: "string",
      workflow: "object",
      source_refs: "array",
      applies_to: "object",
    },
    enumChecks: [],
  },
  {
    family: "context-bundle",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/context-bundle.md",
    exampleGlob: "examples/context/bundles/*.yaml",
    status: "implemented",
    requiredFields: [
      "context_bundle_id",
      "version",
      "title",
      "metadata",
      "applies_to",
      "context_doc_refs",
      "context_rule_refs",
      "context_skill_refs",
      "source_refs",
      "selection_policy",
    ],
    fieldTypes: {
      context_bundle_id: "string",
      version: "number",
      title: "string",
      metadata: "object",
      applies_to: "object",
      context_doc_refs: "array",
      context_rule_refs: "array",
      context_skill_refs: "array",
      source_refs: "array",
      selection_policy: "object",
    },
    enumChecks: [],
  },
  {
    family: "step-policy-profile",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/step-policy-profile.md",
    exampleGlob: "examples/policies/*.yaml",
    status: "implemented",
    requiredFields: ["policy_id", "step_class", "pre_validators", "post_validators", "quality_gate"],
    fieldTypes: {
      policy_id: "string",
      step_class: "string",
      pre_validators: "array",
      post_validators: "array",
      quality_gate: "object",
    },
    enumChecks: [{ field: "step_class", allowedValues: STEP_CLASS_VALUES }],
  },
  {
    family: "adapter-capability-profile",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/adapter-capability-profile.md",
    exampleGlob: "examples/adapters/*.yaml",
    status: "implemented",
    requiredFields: ["adapter_id", "version", "capabilities", "constraints"],
    fieldTypes: {
      adapter_id: "string",
      version: "number",
      capabilities: "object",
      constraints: "object",
    },
    enumChecks: [],
  },
  {
    family: "skill-profile",
    familyGroup: "platform-assets",
    sourceContract: "docs/contracts/skill-profile.md",
    exampleGlob: "examples/skills/*.yaml",
    status: "implemented",
    requiredFields: ["skill_id", "version", "step_class", "summary", "workflow"],
    fieldTypes: {
      skill_id: "string",
      version: "number",
      step_class: "string",
      summary: "string",
      workflow: "array",
    },
    enumChecks: [{ field: "step_class", allowedValues: STEP_CLASS_VALUES }],
  },
  {
    family: "live-run-event",
    familyGroup: "operations",
    sourceContract: "docs/contracts/live-run-event.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: ["event_id", "run_id", "timestamp", "event_type", "payload"],
    fieldTypes: {
      event_id: "string",
      run_id: "string",
      timestamp: "string",
      event_type: "string",
      payload: "object",
    },
    enumChecks: [{ field: "event_type", allowedValues: LIVE_RUN_EVENT_TYPE_VALUES }],
  },
  {
    family: "planner-metrics-snapshot",
    familyGroup: "operations",
    sourceContract: "docs/contracts/planner-metrics-snapshot.md",
    exampleGlob: "examples/reports/planner-metrics-snapshot*.yaml",
    status: "implemented",
    requiredFields: [
      "schema_version",
      "snapshot_id",
      "project_id",
      "generated_at",
      "status",
      "no_data",
      "metric_names",
      "aggregation",
      "source_artifacts",
      "metrics",
      "run_breakdown",
    ],
    fieldTypes: {
      schema_version: "number",
      snapshot_id: "string",
      project_id: "string",
      generated_at: "string",
      status: "string",
      no_data: "boolean",
      metric_names: "array",
      aggregation: "object",
      source_artifacts: "object",
      metrics: "object",
      run_breakdown: "array",
    },
    enumChecks: [{ field: "status", allowedValues: PLANNER_METRICS_STATUS_VALUES }],
  },
  {
    family: "compiler-revision-status",
    familyGroup: "operations",
    sourceContract: "docs/contracts/compiler-revision-status.md",
    exampleGlob: "examples/reports/compiler-revision-status*.yaml",
    status: "implemented",
    requiredFields: [
      "status_id",
      "project_id",
      "compiler_revision_ref",
      "compiler_revision",
      "lifecycle_state",
      "compatibility",
      "decision_history",
      "evidence_links",
      "status",
      "blocking_reasons",
      "created_at",
    ],
    fieldTypes: {
      status_id: "string",
      project_id: "string",
      compiler_revision_ref: "string",
      compiler_revision: "object",
      lifecycle_state: "string",
      compatibility: "object",
      decision_history: "array",
      evidence_links: "object",
      status: "string",
      blocking_reasons: "array",
      created_at: "string",
    },
    enumChecks: [
      { field: "lifecycle_state", allowedValues: COMPILER_REVISION_LIFECYCLE_VALUES },
      { field: "status", allowedValues: COMPILER_REVISION_STATUS_VALUES },
    ],
  },
  {
    family: "learning-loop-scorecard",
    familyGroup: "operations",
    sourceContract: "docs/contracts/learning-loop-scorecard.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: [
      "scorecard_id",
      "project_id",
      "run_id",
      "source_kind",
      "status",
      "summary",
      "evidence_refs",
      "linked_scorecard_refs",
      "linked_eval_suite_refs",
      "linked_harness_capture_refs",
      "linked_backlog_refs",
      "matrix_cell",
      "coverage_follow_up",
      "generated_at",
    ],
    fieldTypes: {
      scorecard_id: "string",
      project_id: "string",
      run_id: "string",
      source_kind: "string",
      status: "string",
      evidence_refs: "array",
      linked_scorecard_refs: "array",
      linked_eval_suite_refs: "array",
      linked_harness_capture_refs: "array",
      linked_backlog_refs: "array",
      matrix_cell: "object",
      coverage_follow_up: "object",
      generated_at: "string",
    },
    enumChecks: [{ field: "status", allowedValues: ["pass", "fail", "aborted", "running", "unknown"] }],
  },
  {
    family: "learning-loop-handoff",
    familyGroup: "operations",
    sourceContract: "docs/contracts/learning-loop-handoff.md",
    exampleGlob: "none",
    status: "implemented",
    requiredFields: [
      "handoff_id",
      "project_id",
      "run_id",
      "run_status",
      "source_kind",
      "scorecard_ref",
      "incident_ref",
      "backlog_refs",
      "quality_refs",
      "evidence_refs",
      "matrix_cell",
      "coverage_follow_up",
      "generated_at",
    ],
    fieldTypes: {
      handoff_id: "string",
      project_id: "string",
      run_id: "string",
      run_status: "string",
      source_kind: "string",
      scorecard_ref: "string",
      backlog_refs: "array",
      quality_refs: "array",
      evidence_refs: "array",
      matrix_cell: "object",
      coverage_follow_up: "object",
      generated_at: "string",
    },
    enumChecks: [],
  },
  {
    family: "live-e2e-provider-variant",
    familyGroup: "operations",
    sourceContract: "docs/contracts/live-e2e-provider-variant.md",
    exampleGlob: "scripts/live-e2e/catalog/providers/*.yaml",
    status: "implemented",
    requiredFields: [
      "provider_variant_id",
      "provider",
      "primary_adapter",
      "fallback_policy",
      "route_override_policy",
    ],
    fieldTypes: {
      provider_variant_id: "string",
      provider: "string",
      primary_adapter: "string",
      fallback_policy: "object",
      route_override_policy: "object",
    },
    enumChecks: [{ field: "provider_variant_id", allowedValues: LIVE_E2E_PROVIDER_VARIANT_VALUES }],
  },
  {
    family: "live-e2e-scenario-policy",
    familyGroup: "operations",
    sourceContract: "docs/contracts/live-e2e-scenario-policy.md",
    exampleGlob: "scripts/live-e2e/catalog/scenarios/*.yaml",
    status: "implemented",
    requiredFields: [
      "scenario_family",
      "required_stages",
      "required_evidence",
      "delivery_mode_policy",
      "release_required",
      "incident_policy",
      "governance_policy",
    ],
    fieldTypes: {
      scenario_family: "string",
      required_stages: "array",
      required_evidence: "array",
      delivery_mode_policy: "string",
      release_required: "boolean",
      incident_policy: "object",
      governance_policy: "object",
    },
    enumChecks: [{ field: "scenario_family", allowedValues: LIVE_E2E_SCENARIO_VALUES }],
  },
  {
    family: "live-e2e-target-catalog",
    familyGroup: "operations",
    sourceContract: "docs/contracts/live-e2e-target-catalog.md",
    exampleGlob: "scripts/live-e2e/catalog/targets/*.yaml",
    status: "implemented",
    requiredFields: [
      "catalog_id",
      "repo",
      "verification",
      "safety_defaults",
      "required_matrix_cells",
      "provider_comparison_pairs",
      "feature_missions",
    ],
    fieldTypes: {
      catalog_id: "string",
      repo: "object",
      verification: "object",
      safety_defaults: "object",
      required_matrix_cells: "array",
      provider_comparison_pairs: "array",
      feature_missions: "array",
    },
    enumChecks: [],
  },
  {
    family: "control-plane-api",
    familyGroup: "operations",
    sourceContract: "docs/contracts/control-plane-api.md",
    exampleGlob: "examples/control-plane-api/*.yaml",
    status: "implemented",
    requiredFields: [
      "api_id",
      "version",
      "binding_mode",
      "deferred_transport_status",
      "read_operations",
      "run_control_operations",
      "ui_lifecycle_operations",
      "live_event_operations",
      "deferred_transport",
    ],
    fieldTypes: {
      api_id: "string",
      version: "number",
      binding_mode: "string",
      deferred_transport_status: "string",
      read_operations: "array",
      run_control_operations: "array",
      ui_lifecycle_operations: "array",
      live_event_operations: "array",
      deferred_transport: "object",
    },
    enumChecks: [
      { field: "binding_mode", allowedValues: ["hybrid-module-and-detached-http-sse"] },
      { field: "deferred_transport_status", allowedValues: ["implemented"] },
    ],
  },
]);

export const EXAMPLE_FAMILY_RESOLUTION_RULES = Object.freeze([
  { regex: /^examples\/adapters\/[^/]+\.ya?ml$/, family: "adapter-capability-profile" },
  { regex: /^examples\/context\/bundles\/[^/]+\.ya?ml$/, family: "context-bundle" },
  { regex: /^examples\/context\/compiled\/[^/]+\.ya?ml$/, family: "compiled-context-artifact" },
  { regex: /^examples\/context\/docs\/[^/]+\.ya?ml$/, family: "context-doc" },
  { regex: /^examples\/context\/rules\/[^/]+\.ya?ml$/, family: "context-rule" },
  { regex: /^examples\/context\/skills\/[^/]+\.ya?ml$/, family: "context-skill" },
  { regex: /^examples\/control-plane-api\/[^/]+\.ya?ml$/, family: "control-plane-api" },
  { regex: /^examples\/delivery-manifest[^/]*\.ya?ml$/, family: "delivery-manifest" },
  { regex: /^examples\/reports\/discovery-research-report[^/]*\.ya?ml$/, family: "discovery-research-report" },
  { regex: /^examples\/reports\/incident-backfill-proposal[^/]*\.ya?ml$/, family: "incident-backfill-proposal" },
  { regex: /^examples\/reports\/planner-metrics-snapshot[^/]*\.ya?ml$/, family: "planner-metrics-snapshot" },
  { regex: /^examples\/reports\/compiler-revision-status[^/]*\.ya?ml$/, family: "compiler-revision-status" },
  { regex: /^examples\/packets\/delivery-plan-[^/]+\.ya?ml$/, family: "delivery-plan" },
  { regex: /^examples\/packets\/intake-request-body[^/]*\.ya?ml$/, family: "intake-request-body" },
  { regex: /^examples\/eval\/dataset-[^/]+\.ya?ml$/, family: "dataset" },
  { regex: /^examples\/eval\/report-[^/]+\.sample\.ya?ml$/, family: "evaluation-report" },
  { regex: /^examples\/eval\/suite-[^/]+\.ya?ml$/, family: "evaluation-suite" },
  { regex: /^examples\/reports\/live-e2e-observation-report[^/]*\.ya?ml$/, family: "live-e2e-observation-report" },
  { regex: /^examples\/reports\/multirepo-coordination-status[^/]*\.ya?ml$/, family: "multirepo-coordination-status" },
  { regex: /^examples\/reports\/review-decision[^/]*\.ya?ml$/, family: "review-decision" },
  { regex: /^examples\/reports\/runtime-harness-report[^/]*\.ya?ml$/, family: "runtime-harness-report" },
  { regex: /^examples\/packets\/wave-ticket-[^/]+\.ya?ml$/, family: "wave-ticket" },
  { regex: /^examples\/packets\/handoff-[^/]+\.ya?ml$/, family: "handoff-packet" },
  { regex: /^examples\/packets\/promotion-decision-[^/]+\.ya?ml$/, family: "promotion-decision" },
  { regex: /^examples\/packets\/release-[^/]+\.ya?ml$/, family: "release-packet" },
  { regex: /^examples\/policies\/[^/]+\.ya?ml$/, family: "step-policy-profile" },
  { regex: /^examples\/project-analysis-report\.sample\.ya?ml$/, family: "project-analysis-report" },
  { regex: /^examples\/project[^/]*\.aor\.ya?ml$/, family: "project-profile" },
  { regex: /^examples\/prompts\/[^/]+\.ya?ml$/, family: "prompt-bundle" },
  { regex: /^examples\/routes\/[^/]+\.ya?ml$/, family: "provider-route-profile" },
  { regex: /^examples\/skills\/[^/]+\.ya?ml$/, family: "skill-profile" },
  { regex: /^examples\/wrappers\/[^/]+\.ya?ml$/, family: "wrapper-profile" },
]);
