export const RUNTIME_ROOT_DIRNAME = ".aor";

const COMMAND_DEFINITIONS = Object.freeze([
  {
    command: "doctor",
    category: "guided-first-run",
    status: "implemented",
    summary: "Inspect installed-user environment and repository readiness without mutating runtime state.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd)",
      "--runtime-root <path> (optional)",
      "--json (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "guided_command",
      "guided_stage",
      "guided_status",
      "guided_summary",
      "guided_readiness",
      "guided_actionable_blockers",
      "guided_recommended_commands",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: [],
  },
  {
    command: "onboard",
    category: "guided-first-run",
    status: "implemented",
    summary: "Guided first-run wrapper over project init for preparing a target repository.",
    inputs: [
      "<repo> (optional positional project ref)",
      "--project-ref <path> (optional, alternative to positional repo)",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-mode <bundled|materialized> (optional, defaults to bundled, materialized copies example assets into the target repo)",
      "--materialize-project-profile (optional)",
      "--bootstrap-template <template_id|path> (optional)",
      "--materialize-bootstrap-assets (optional)",
      "--repo-build-command <cmd> (optional, repeatable)",
      "--repo-lint-command <cmd> (optional, repeatable)",
      "--repo-test-command <cmd> (optional, repeatable)",
      "--json (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "project_profile_ref",
      "runtime_layout",
      "runtime_state_file",
      "artifact_packet_id",
      "artifact_packet_file",
      "artifact_packet_body_file",
      "onboarding_report_id",
      "onboarding_report_file",
      "asset_mode",
      "registry_roots",
      "bootstrap_materialization_status",
      "materialized_project_profile_file",
      "materialized_bootstrap_assets_root",
      "bootstrap_materialization_idempotent",
      "guided_command",
      "guided_stage",
      "guided_status",
      "guided_summary",
      "guided_low_level_command",
      "guided_actionable_blockers",
      "guided_recommended_commands",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: ["project-profile", "onboarding-report"],
  },
  {
    command: "app",
    category: "guided-first-run",
    status: "implemented",
    summary: "Launch the optional local web console while keeping headless CLI/API operation valid.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd)",
      "--runtime-root <path> (optional)",
      "--host <host> (optional, default 127.0.0.1)",
      "--port <number> (optional, default 0)",
      "--open <true|false> (optional, default true)",
      "--smoke <true|false> (optional)",
      "--json (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "guided_command",
      "guided_stage",
      "guided_status",
      "guided_summary",
      "guided_low_level_command",
      "guided_actionable_blockers",
      "guided_recommended_commands",
      "guided_web_surface",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: [],
  },
  {
    command: "next",
    category: "guided-first-run",
    status: "implemented",
    summary: "Resolve one deterministic next action from onboarding, mission, run, and policy evidence.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd)",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--json (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "guided_command",
      "guided_stage",
      "guided_status",
      "guided_summary",
      "guided_low_level_command",
      "guided_readiness",
      "guided_actionable_blockers",
      "guided_recommended_commands",
      "next_action_report_id",
      "next_action_report_file",
      "next_action_status",
      "next_action_primary",
      "next_action_blockers",
      "next_action_evidence_refs",
      "next_action_mission_state",
      "next_action_closure_state",
      "next_action_bounded_execution",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: ["next-action-report"],
  },
  {
    command: "mission create",
    category: "guided-first-run",
    status: "implemented",
    summary: "Capture guided mission intake as an intake-request packet without creating a parallel mission schema.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd)",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--mission-id <id> (optional)",
      "--title <text> (optional)",
      "--brief <text> (optional)",
      "--goal <text> (optional, repeatable)",
      "--constraint <text> (optional, repeatable)",
      "--kpi <kpi_id:name:target[:measurement]> (optional, repeatable)",
      "--dod <text> (optional, repeatable)",
      "--allowed-path <glob[,glob...]> (optional, repeatable)",
      "--forbidden-path <glob[,glob...]> (optional, repeatable)",
      "--delivery-mode <no-write|patch-only|local-branch|fork-first-pr> (optional, defaults to no-write)",
      "--request-file <path> (optional)",
      "--source-kind <local-issue|local-prd|local-rfc|local-note|local-mail> (optional)",
      "--source-ref <path|ref> (optional)",
      "--json (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "project_profile_ref",
      "runtime_layout",
      "runtime_state_file",
      "artifact_packet_id",
      "artifact_packet_file",
      "artifact_packet_body_file",
      "product_intake",
      "product_intake_completeness",
      "product_intake_source_refs",
      "delivery_mode",
      "guided_command",
      "guided_stage",
      "guided_status",
      "guided_summary",
      "guided_low_level_command",
      "guided_actionable_blockers",
      "guided_recommended_commands",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: ["artifact-packet", "intake-request-body"],
  },
  {
    command: "project init",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Discover project root, load profile, and initialize runtime-root layout.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd discovery)",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-mode <bundled|materialized> (optional, defaults to bundled for clean onboarding)",
      "--materialize-project-profile (optional)",
      "--bootstrap-template <template_id|path> (optional)",
      "--materialize-bootstrap-assets (optional)",
      "--repo-build-command <cmd> (optional, repeatable)",
      "--repo-lint-command <cmd> (optional, repeatable)",
      "--repo-test-command <cmd> (optional, repeatable)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "project_profile_ref",
      "runtime_layout",
      "runtime_state_file",
      "artifact_packet_id",
      "artifact_packet_file",
      "artifact_packet_body_file",
      "onboarding_report_id",
      "onboarding_report_file",
      "asset_mode",
      "registry_roots",
      "bootstrap_materialization_status",
      "materialized_project_profile_file",
      "materialized_bootstrap_assets_root",
      "bootstrap_materialization_idempotent",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: ["project-profile", "onboarding-report"],
  },
  {
    command: "project analyze",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Analyze repository facts and write durable project-analysis report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "analysis_report_id",
      "analysis_report_file",
      "route_resolution_file",
      "route_resolution_steps",
      "asset_resolution_file",
      "asset_resolution_steps",
      "policy_resolution_file",
      "policy_resolution_steps",
      "evaluation_registry_file",
      "evaluation_registry_suites",
      "evaluation_registry_datasets",
      "discovery_research_report_id",
      "discovery_research_report_file",
      "discovery_research_status",
      "discovery_research_adr_ready",
      "discovery_research_open_questions",
      "discovery_completeness_status",
      "discovery_completeness_blocking",
      "discovery_completeness_checks",
      "architecture_traceability",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["project-analysis-report", "discovery-research-report"],
  },
  {
    command: "project validate",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Run deterministic validation checks and persist validation-report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--require-approved-handoff (optional)",
      "--handoff-packet <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "validation_report_id",
      "validation_report_file",
      "validation_status",
      "validation_blocking",
      "handoff_gate_enforced",
      "handoff_gate_status",
      "handoff_gate_blocking",
      "handoff_packet_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["validation-report"],
  },
  {
    command: "project verify",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Validate command contract inputs for bounded verify preflight flow.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--require-validation-pass (optional)",
      "--verification-label <label> (optional)",
      "--repo-build-command <cmd> (optional, repeatable)",
      "--repo-lint-command <cmd> (optional, repeatable)",
      "--repo-test-command <cmd> (optional, repeatable)",
      "--routed-dry-run-step <step_class> (optional)",
      "--routed-live-step <step_class> (optional)",
      "--approved-handoff-ref <ref> (optional, required for live non-no-write flow)",
      "--promotion-evidence-refs <ref[,ref...]> (optional, required for live non-no-write flow)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "validation_gate_enforced",
      "validation_gate_status",
      "verification_label",
      "verify_summary_file",
      "step_result_files",
      "routed_step_result_id",
      "routed_step_result_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["step-result"],
  },
  {
    command: "eval run",
    category: "quality-workflows",
    status: "implemented",
    summary: "Run an offline evaluation suite and persist a durable evaluation-report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--suite-ref <suite_id@vN> (optional, defaults to project eval policy)",
      "--subject-ref <subject_type://target>",
      "--subject-version <version> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "evaluation_report_id",
      "evaluation_report_file",
      "evaluation_status",
      "evaluation_blocking",
      "evaluation_suite_ref",
      "evaluation_subject_ref",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "subject-ref"],
    contractFamilies: ["evaluation-report"],
  },
  {
    command: "harness replay",
    category: "quality-workflows",
    status: "implemented",
    summary: "Replay one harness capture against current routed assets and persist a durable replay report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--capture-file <path>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "harness_replay_id",
      "harness_replay_file",
      "harness_replay_status",
      "harness_replay_compatible",
      "harness_replay_blocked_next_step",
      "harness_replay_evidence_refs",
      "harness_replay_evaluation_report_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "capture-file"],
    contractFamilies: ["step-result", "evaluation-report"],
  },
  {
    command: "harness certify",
    category: "quality-workflows",
    status: "implemented",
    summary: "Certify a changed asset set from deterministic validation, eval, harness replay, and baseline comparison evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-ref <asset://target>",
      "--subject-ref <subject_type://target>",
      "--suite-ref <suite_id@vN> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--from-channel <channel> (optional, defaults to candidate)",
      "--to-channel <channel> (optional, defaults to stable)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "promotion_decision_id",
      "promotion_decision_file",
      "promotion_decision_status",
      "certification_evaluation_report_file",
      "certification_harness_capture_file",
      "certification_harness_replay_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "asset-ref", "subject-ref"],
    contractFamilies: ["promotion-decision"],
  },
  {
    command: "asset promote",
    category: "quality-workflows",
    status: "implemented",
    summary: "Promote one asset through certification evidence with explicit governance and rollout semantics.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-ref <asset://target>",
      "--subject-ref <subject_type://target>",
      "--suite-ref <suite_id@vN> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--from-channel <channel> (optional, defaults to candidate)",
      "--to-channel <channel> (optional, defaults to stable)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "promotion_decision_id",
      "promotion_decision_file",
      "promotion_decision_status",
      "promotion_from_channel",
      "promotion_to_channel",
      "promotion_rollout_action",
      "promotion_governance_checks",
      "certification_evaluation_report_file",
      "certification_harness_capture_file",
      "certification_harness_replay_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "asset-ref", "subject-ref"],
    contractFamilies: ["promotion-decision"],
  },
  {
    command: "asset freeze",
    category: "quality-workflows",
    status: "implemented",
    summary: "Evaluate freeze transition guardrails for one asset and emit a durable promotion decision.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-ref <asset://target>",
      "--subject-ref <subject_type://target>",
      "--suite-ref <suite_id@vN> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--from-channel <channel> (optional, defaults to stable)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "promotion_decision_id",
      "promotion_decision_file",
      "promotion_decision_status",
      "promotion_from_channel",
      "promotion_to_channel",
      "promotion_rollout_action",
      "promotion_governance_checks",
      "certification_evaluation_report_file",
      "certification_harness_capture_file",
      "certification_harness_replay_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "asset-ref", "subject-ref"],
    contractFamilies: ["promotion-decision"],
  },
  {
    command: "compiler revision",
    category: "quality-workflows",
    status: "implemented",
    summary: "Inspect or change one compiler revision lifecycle with durable status and decision-history evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--compiler-revision-ref <compiler-revision://id@vN>",
      "--action <inspect|promote|freeze|demote> (optional, defaults to inspect)",
      "--promotion-decision-ref <evidence://...> (optional, required for promote/freeze/demote readiness)",
      "--compiled-context-refs <ref[,ref...]> (optional)",
      "--evaluation-refs <ref[,ref...]> (optional)",
      "--incident-refs <ref[,ref...]> (optional)",
      "--certification-evidence-refs <ref[,ref...]> (optional)",
      "--compatibility-status <compatible|incompatible|unknown> (optional, defaults to unknown)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "runtime_layout",
      "runtime_state_file",
      "compiler_revision_status_id",
      "compiler_revision_status_file",
      "compiler_revision_status_ref",
      "compiler_revision_ref",
      "compiler_revision_lifecycle_state",
      "compiler_revision_status",
      "compiler_revision_blocking",
      "compiler_revision_blocking_reasons",
      "compiler_revision_compatibility",
      "compiler_revision_decision_history",
      "compiler_revision_records",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "compiler-revision-ref"],
    contractFamilies: ["compiler-revision-status"],
  },
  {
    command: "handoff prepare",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Materialize wave-ticket and pending handoff-packet from approved bootstrap artifact.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--ticket-id <id> (optional)",
      "--approved-artifact <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "wave_ticket_id",
      "wave_ticket_file",
      "handoff_packet_id",
      "handoff_packet_file",
      "handoff_status",
      "handoff_approval_state",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["wave-ticket", "handoff-packet"],
  },
  {
    command: "handoff approve",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Approve handoff-packet with explicit approval reference for execution gating.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--handoff-packet <path> (optional)",
      "--approval-ref <ref>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "handoff_packet_id",
      "handoff_packet_file",
      "handoff_status",
      "handoff_approval_state",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "approval-ref"],
    contractFamilies: ["handoff-packet"],
  },
  {
    command: "intake create",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Create one intake-request artifact packet with feature intent and optional mission traceability.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--request-title <text> (optional)",
      "--request-brief <text> (optional)",
      "--request-constraints <text[,text...]> (optional, repeatable)",
      "--request-file <path> (optional)",
      "--source-kind <local-issue|local-prd|local-rfc|local-note|local-mail> (optional)",
      "--source-ref <path|ref> (optional)",
      "--mission-id <id> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "project_profile_ref",
      "runtime_layout",
      "runtime_state_file",
      "artifact_packet_id",
      "artifact_packet_file",
      "artifact_packet_body_file",
      "product_intake",
      "product_intake_completeness",
      "product_intake_source_refs",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["artifact-packet", "intake-request-body"],
  },
  {
    command: "discovery run",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Run discovery analysis flow and persist route, asset, policy, and analysis reports.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--input-packet <path|ref> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "analysis_report_id",
      "analysis_report_file",
      "route_resolution_file",
      "route_resolution_steps",
      "asset_resolution_file",
      "asset_resolution_steps",
      "policy_resolution_file",
      "policy_resolution_steps",
      "evaluation_registry_file",
      "evaluation_registry_suites",
      "evaluation_registry_datasets",
      "discovery_research_report_id",
      "discovery_research_report_file",
      "discovery_research_status",
      "discovery_research_adr_ready",
      "discovery_research_open_questions",
      "discovery_completeness_status",
      "discovery_completeness_blocking",
      "discovery_completeness_checks",
      "architecture_traceability",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["project-analysis-report", "discovery-research-report"],
  },
  {
    command: "spec build",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Execute routed dry-run spec step and write durable step-result evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "routed_step_result_id",
      "routed_step_result_file",
      "step_result_files",
      "discovery_completeness_status",
      "discovery_completeness_blocking",
      "discovery_completeness_checks",
      "discovery_research_gate",
      "discovery_research_status",
      "discovery_research_adr_ready",
      "discovery_research_open_questions",
      "architecture_traceability",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["step-result", "discovery-research-report"],
  },
  {
    command: "wave create",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Materialize wave-ticket and pending handoff-packet for bounded implementation planning.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--ticket-id <id> (optional)",
      "--approved-artifact <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "wave_ticket_id",
      "wave_ticket_file",
      "handoff_packet_id",
      "handoff_packet_file",
      "handoff_status",
      "handoff_approval_state",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["wave-ticket", "handoff-packet"],
  },
  {
    command: "run start",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Start one execution run, emit control-plane events, and materialize routed execution evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--target-step <step_class> (optional, defaults to implement)",
      "--require-validation-pass <true|false> (optional, defaults to true)",
      "--approved-handoff-ref <ref> (optional)",
      "--promotion-evidence-refs <ref[,ref...]> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_control_action",
      "run_control_run_id",
      "run_control_state",
      "run_control_state_file",
      "run_control_audit_id",
      "run_control_audit_file",
      "run_control_blocked",
      "run_control_guardrails",
      "run_control_transition",
      "primary_event_id",
      "evidence_event_id",
      "routed_step_result_id",
      "routed_step_result_file",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["live-run-event", "step-result", "runtime-harness-report"],
  },
  {
    command: "run pause",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Pause one active run-control lifecycle with deterministic transition and durable audit trace.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_control_action",
      "run_control_run_id",
      "run_control_state",
      "run_control_state_file",
      "run_control_audit_id",
      "run_control_audit_file",
      "run_control_blocked",
      "run_control_guardrails",
      "run_control_transition",
      "primary_event_id",
      "evidence_event_id",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["live-run-event"],
  },
  {
    command: "run resume",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Resume one paused run-control lifecycle with deterministic transition and durable audit trace.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_control_action",
      "run_control_run_id",
      "run_control_state",
      "run_control_state_file",
      "run_control_audit_id",
      "run_control_audit_file",
      "run_control_blocked",
      "run_control_guardrails",
      "run_control_transition",
      "primary_event_id",
      "evidence_event_id",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["live-run-event"],
  },
  {
    command: "run steer",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Steer one active run toward an explicit target step with policy and approval guardrails.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--target-step <step_class> (required by guardrail)",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_control_action",
      "run_control_run_id",
      "run_control_state",
      "run_control_state_file",
      "run_control_audit_id",
      "run_control_audit_file",
      "run_control_blocked",
      "run_control_guardrails",
      "run_control_transition",
      "primary_event_id",
      "evidence_event_id",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["live-run-event"],
  },
  {
    command: "run cancel",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Cancel one active run-control lifecycle with explicit policy gating and audit evidence.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_control_action",
      "run_control_run_id",
      "run_control_state",
      "run_control_state_file",
      "run_control_audit_id",
      "run_control_audit_file",
      "run_control_blocked",
      "run_control_guardrails",
      "run_control_transition",
      "primary_event_id",
      "evidence_event_id",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["live-run-event"],
  },
  {
    command: "run answer",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Submit an audited answer for one unresolved runner-requested interaction without streaming raw answer text.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--interaction-id <id>",
      "--answer <text> (optional when --answer-evidence-ref is supplied)",
      "--decision approve_once|deny|approve_for_run (optional)",
      "--answer-evidence-ref <ref> (optional)",
      "--reason <text> (optional)",
      "--approval-ref <ref> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "runtime_layout",
      "interaction_answer",
      "stream_log_file",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id", "interaction-id"],
    contractFamilies: ["step-result", "live-run-event"],
  },
  {
    command: "run status",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Inspect run summaries, selected-run event/policy history, and optionally follow live events.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--follow <true|false> (optional)",
      "--after-event-id <event_id> (optional)",
      "--max-replay <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_summaries",
      "run_event_history",
      "run_policy_history",
      "strategic_snapshot",
      "follow_mode",
      "stream_protocol",
      "stream_backpressure",
      "replay_events",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: [
      "live-run-event",
      "step-result",
      "delivery-plan",
      "delivery-manifest",
      "release-packet",
      "promotion-decision",
      "planner-metrics-snapshot",
      "finance-monitoring-snapshot",
    ],
  },
  {
    command: "deliver prepare",
    category: "delivery-and-release",
    status: "implemented",
    summary: "Materialize policy-bounded delivery artifacts and write-back intent outputs.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--mode <mode> (optional, one of no-write, patch-only, local-branch, fork-first-pr)",
      "--quality-gate-mode <strict|observe> (optional, default strict)",
      "--require-review-decision (optional)",
      "--approved-handoff-ref <ref> (optional)",
      "--promotion-evidence-refs <ref[,ref...]> (optional)",
      "--coordination-evidence-refs <ref[,ref...]> (optional)",
      "--coordination-lock-evidence-refs <ref[,ref...]> (optional)",
      "--cross-repo-validation-refs <ref[,ref...]> (optional)",
      "--rerun-of-run-id <id> (optional)",
      "--rerun-failed-step <step_id> (optional)",
      "--rerun-packet-boundary <delivery-manifest|release-packet> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--ticket-id <id> (optional)",
      "--branch-name <name> (optional)",
      "--commit-message <text> (optional)",
      "--fork-owner <owner> (optional)",
      "--fork-remote-url <url> (optional)",
      "--network-write <true|false> (optional, default false)",
      "--base-ref <ref> (optional)",
      "--pr-title <text> (optional)",
      "--pr-body <text> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "delivery_plan_id",
      "delivery_plan_file",
      "delivery_plan_status",
      "delivery_mode",
      "delivery_quality_gate_mode",
      "delivery_quality_gate_status",
      "delivery_quality_gate_findings",
      "delivery_blocking",
      "delivery_blocking_reasons",
      "delivery_governance_decision",
      "delivery_coordination",
      "delivery_rerun_recovery",
      "delivery_transcript_file",
      "delivery_manifest_id",
      "delivery_manifest_file",
      "release_packet_id",
      "release_packet_file",
      "release_packet_status",
      "delivery_writeback_result",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "review_decision_id",
      "review_decision_file",
      "review_decision",
      "review_decision_gate",
      "review_decision_reason",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["delivery-plan", "delivery-manifest", "release-packet", "runtime-harness-report", "review-decision"],
  },
  {
    command: "release prepare",
    category: "delivery-and-release",
    status: "implemented",
    summary: "Prepare release packet lineage from guarded delivery policy and evidence preconditions.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--mode <mode> (optional, one of no-write, patch-only, local-branch, fork-first-pr)",
      "--require-review-decision (optional)",
      "--approved-handoff-ref <ref> (optional)",
      "--promotion-evidence-refs <ref[,ref...]> (optional)",
      "--coordination-evidence-refs <ref[,ref...]> (optional)",
      "--coordination-lock-evidence-refs <ref[,ref...]> (optional)",
      "--cross-repo-validation-refs <ref[,ref...]> (optional)",
      "--rerun-of-run-id <id> (optional)",
      "--rerun-failed-step <step_id> (optional)",
      "--rerun-packet-boundary <delivery-manifest|release-packet> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--ticket-id <id> (optional)",
      "--branch-name <name> (optional)",
      "--commit-message <text> (optional)",
      "--fork-owner <owner> (optional)",
      "--fork-remote-url <url> (optional)",
      "--network-write <true|false> (optional, default false)",
      "--base-ref <ref> (optional)",
      "--pr-title <text> (optional)",
      "--pr-body <text> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "delivery_plan_id",
      "delivery_plan_file",
      "delivery_plan_status",
      "delivery_mode",
      "delivery_blocking",
      "delivery_blocking_reasons",
      "delivery_governance_decision",
      "delivery_coordination",
      "delivery_rerun_recovery",
      "delivery_transcript_file",
      "delivery_manifest_id",
      "delivery_manifest_file",
      "release_packet_id",
      "release_packet_file",
      "release_packet_status",
      "delivery_writeback_result",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "review_decision_id",
      "review_decision_file",
      "review_decision",
      "review_decision_gate",
      "review_decision_reason",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["delivery-plan", "delivery-manifest", "release-packet", "runtime-harness-report", "review-decision"],
  },
  {
    command: "multirepo lock",
    category: "delivery-and-release",
    status: "implemented",
    summary: "Declare, release, or inspect bounded multirepo scoped locks and cross-repo validation status.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--action <acquire|release|inspect> (optional, default inspect)",
      "--run-id <id> (optional)",
      "--owner-ref <ref> (required for acquire, optional for release)",
      "--repo-ids <id[,id...]> (optional)",
      "--path-globs <glob[,glob...]> (optional, default **)",
      "--duration-minutes <minutes> (optional, default 60)",
      "--lock-id <id> (optional)",
      "--release-evidence-refs <ref[,ref...]> (optional)",
      "--repo-validation-refs <repo=ref[,repo=ref...]> (optional)",
      "--failed-repo-ids <id[,id...]> (optional)",
      "--integration-validation-refs <ref[,ref...]> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "runtime_layout",
      "runtime_state_file",
      "multirepo_coordination_id",
      "multirepo_coordination_file",
      "multirepo_coordination_ref",
      "multirepo_coordination_status",
      "multirepo_coordination_blocking",
      "multirepo_coordination_blocking_reasons",
      "multirepo_lock_state",
      "multirepo_cross_repo_validation",
      "multirepo_coordination_records",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["multirepo-coordination-status"],
  },
  {
    command: "packet show",
    category: "delivery-and-release",
    status: "implemented",
    summary: "List packet artifacts from runtime storage through the shared API read surface.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--family <contract_family|all> (optional)",
      "--limit <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "packet_artifacts",
      "selected_family",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: [
      "artifact-packet",
      "wave-ticket",
      "handoff-packet",
      "delivery-plan",
      "delivery-manifest",
      "release-packet",
    ],
  },
  {
    command: "evidence show",
    category: "delivery-and-release",
    status: "implemented",
    summary: "Inspect step results, quality artifacts, and delivery evidence through one read-only command.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "step_results",
      "quality_artifacts",
      "delivery_manifests",
      "promotion_decisions",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: [
      "step-result",
      "validation-report",
      "evaluation-report",
      "review-report",
      "review-decision",
      "runtime-harness-report",
      "multirepo-coordination-status",
      "compiler-revision-status",
      "learning-loop-scorecard",
      "learning-loop-handoff",
      "incident-report",
      "incident-backfill-proposal",
      "promotion-decision",
      "delivery-manifest",
      "release-packet",
    ],
  },
  {
    command: "incident open",
    category: "incidents-and-audit",
    status: "implemented",
    summary: "Create a durable incident-report linked to one run and its evidence lineage.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--summary <text>",
      "--severity <level> (optional, defaults to high)",
      "--status <state> (optional, defaults to open)",
      "--linked-asset-refs <ref[,ref...]> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "incident_id",
      "incident_report_file",
      "incident_status",
      "incident_run_ref",
      "incident_linked_asset_refs",
      "audit_evidence_refs",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id", "summary"],
    contractFamilies: ["incident-report", "promotion-decision", "delivery-manifest", "release-packet", "step-result"],
  },
  {
    command: "incident backfill",
    category: "incidents-and-audit",
    status: "implemented",
    summary: "Create a reviewed proposal for turning incident and learning-loop evidence into dataset or suite cases.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--incident-id <id>",
      "--suite-ref <suite_id@vN> (optional, defaults to the first registry suite)",
      "--case-id <id> (optional)",
      "--proposal-state <proposed|approved|rejected> (optional, defaults to proposed)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "incident_id",
      "incident_report_file",
      "incident_status",
      "incident_run_ref",
      "incident_linked_asset_refs",
      "incident_backfill_proposal_id",
      "incident_backfill_proposal_file",
      "incident_backfill_proposal_state",
      "incident_backfill_suite_ref",
      "incident_backfill_dataset_ref",
      "incident_backfill_case_ids",
      "incident_backfill_review_required",
      "audit_evidence_refs",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "incident-id"],
    contractFamilies: ["incident-backfill-proposal", "incident-report", "learning-loop-handoff", "learning-loop-scorecard", "evaluation-suite", "dataset"],
  },
  {
    command: "incident recertify",
    category: "incidents-and-audit",
    status: "implemented",
    summary: "Apply recertify/hold/re-enable incident transitions with platform rollback-safe gating.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--incident-id <id>",
      "--decision <recertify|hold|re-enable> (optional, defaults to recertify)",
      "--promotion-ref <evidence://...> (optional, required for verified re-enable when run linkage is ambiguous)",
      "--run-id <id> (optional)",
      "--reason <text> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "incident_id",
      "incident_report_file",
      "incident_status",
      "incident_run_ref",
      "incident_linked_asset_refs",
      "incident_recertification_decision",
      "incident_recertification_from_status",
      "incident_recertification_to_status",
      "incident_recertification_promotion_ref",
      "incident_recertification_gate",
      "incident_recertification_platform_action",
      "incident_recertification_platform_linkage",
      "incident_recertification_rollback_required",
      "incident_recertification_finance_evidence_refs",
      "incident_recertification_quality_evidence_refs",
      "incident_recertification_finance_evidence_root",
      "incident_recertification_quality_evidence_root",
      "audit_evidence_refs",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "incident-id"],
    contractFamilies: ["incident-report", "promotion-decision", "step-result"],
  },
  {
    command: "incident show",
    category: "incidents-and-audit",
    status: "implemented",
    summary: "Inspect incident reports by incident_id or run_id with run-linked evidence refs.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--incident-id <id> (optional)",
      "--run-id <id> (optional)",
      "--limit <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "incident_records",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["incident-report", "incident-backfill-proposal"],
  },
  {
    command: "audit runs",
    category: "incidents-and-audit",
    status: "implemented",
    summary:
      "Produce run-centric audit snapshots linking run refs to incident/promotion evidence plus durable finance cost/latency signals.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--limit <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_audit_records",
      "run_audit_records.finance_evidence",
      "run_audit_records.scenario_family",
      "run_audit_records.provider_variant_id",
      "run_audit_records.feature_size",
      "run_audit_records.matrix_cell",
      "run_audit_records.provider_execution_status",
      "run_audit_records.feature_size_fit_status",
      "audit_evidence_refs",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["incident-report", "promotion-decision", "delivery-manifest", "release-packet", "step-result"],
  },
  {
    command: "finance monitor",
    category: "incidents-and-audit",
    status: "implemented",
    summary:
      "Read finance analytics and production monitoring signals without mixing certification, rehearsal, and production evidence.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "finance_monitoring_snapshot",
      "finance_analytics",
      "production_monitoring",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["finance-monitoring-snapshot", "step-result", "promotion-decision", "live-run-event"],
  },
  {
    command: "ui attach",
    category: "ui-lifecycle",
    status: "implemented",
    summary: "Attach optional web operator surface with explicit lifecycle state and headless-safe semantics.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--control-plane <url> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "ui_lifecycle_action",
      "ui_lifecycle_state",
      "ui_lifecycle_state_file",
      "ui_lifecycle_idempotent",
      "ui_lifecycle_connection_state",
      "ui_lifecycle_headless_safe",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["live-run-event"],
  },
  {
    command: "review run",
    category: "quality-workflows",
    status: "implemented",
    summary: "Materialize one report-only review verdict for run-linked discovery, artifact, and code quality.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "review_report_id",
      "review_report_file",
      "review_overall_status",
      "review_recommendation",
      "review_feature_size_fit_status",
      "review_provider_traceability_status",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["review-report", "runtime-harness-report"],
  },
  {
    command: "review decide",
    category: "quality-workflows",
    status: "implemented",
    summary: "Record one durable approve, hold, or request-repair decision for run-linked review evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--decision <approve|hold|request-repair>",
      "--reason <text> (optional)",
      "--decider-ref <ref> (optional, defaults to operator://cli)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "review_decision_id",
      "review_decision_file",
      "review_decision",
      "review_decision_gate",
      "review_decision_reason",
      "review_decision_evidence_refs",
      "review_report_id",
      "review_report_file",
      "review_overall_status",
      "review_recommendation",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id", "decision"],
    contractFamilies: ["review-decision", "review-report", "runtime-harness-report"],
  },
  {
    command: "learning handoff",
    category: "incident-and-audit",
    status: "implemented",
    summary: "Close one run into public learning-loop scorecard and handoff artifacts.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "learning_loop_scorecard_file",
      "learning_loop_handoff_file",
      "incident_report_file",
      "runtime_harness_report_id",
      "runtime_harness_report_file",
      "runtime_harness_overall_decision",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["learning-loop-scorecard", "learning-loop-handoff", "incident-report", "runtime-harness-report"],
  },
  {
    command: "ui detach",
    category: "ui-lifecycle",
    status: "implemented",
    summary: "Detach optional web operator surface without interrupting headless CLI/API operation.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "ui_lifecycle_action",
      "ui_lifecycle_state",
      "ui_lifecycle_state_file",
      "ui_lifecycle_idempotent",
      "ui_lifecycle_connection_state",
      "ui_lifecycle_headless_safe",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["live-run-event"],
  },
]);

export function getCliCommandCatalog() {
  return COMMAND_DEFINITIONS.map((definition) => ({ ...definition }));
}

export function getImplementedCommands() {
  return getCliCommandCatalog().filter((definition) => definition.status === "implemented");
}

export function getPlannedCommands() {
  return getCliCommandCatalog().filter((definition) => definition.status === "planned");
}

export function getCommandDefinition(command) {
  return getCliCommandCatalog().find((definition) => definition.command === command) ?? null;
}
