import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const BOOTSTRAP_OWNED_PREFIXES = ["examples/", "context/", ".aor/"];
const BOOTSTRAP_OWNED_FILES = new Set(["project.aor.yaml"]);
const RUNNER_OWNED_STATE_PREFIXES = [".codex/", ".claude/", ".qwen/", ".opencode/"];
const DIAGNOSTIC_SIDE_EFFECT_SIGNATURES = ["# TLS secrets log file, generated by OpenSSL / Python"];

/**
 * @param {unknown} value
 * @returns {string | null}
 */
function asString(value) {
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

/**
 * @param {unknown} value
 * @returns {string[]}
 */
function asStringArray(value) {
  return Array.isArray(value)
    ? value.filter((entry) => typeof entry === "string" && entry.trim().length > 0).map((entry) => entry.trim())
    : [];
}

/**
 * @param {unknown} value
 * @returns {Record<string, unknown>}
 */
function asRecord(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? /** @type {Record<string, unknown>} */ (value)
    : {};
}

/**
 * @param {unknown} value
 * @returns {string[]}
 */
function uniqueStrings(value) {
  return [...new Set(asStringArray(value))];
}

/**
 * @param {string} filePath
 * @returns {Record<string, unknown> | null}
 */
function readJsonFile(filePath) {
  try {
    return /** @type {Record<string, unknown>} */ (JSON.parse(fs.readFileSync(filePath, "utf8")));
  } catch {
    return null;
  }
}

/**
 * @param {string} dirPath
 * @returns {string[]}
 */
function listJsonFiles(dirPath) {
  if (!fs.existsSync(dirPath)) {
    return [];
  }
  return fs
    .readdirSync(dirPath)
    .filter((entry) => entry.endsWith(".json"))
    .map((entry) => path.join(dirPath, entry))
    .sort((left, right) => fs.statSync(right).mtimeMs - fs.statSync(left).mtimeMs);
}

/**
 * @param {string} root
 * @returns {{ available: boolean, changedPaths: string[] }}
 */
export function listChangedPaths(root) {
  if (!fs.existsSync(root)) {
    return { available: false, changedPaths: [] };
  }
  const run = spawnSync("git", ["status", "--porcelain", "--untracked-files=all", "--", ".", ":!.aor/**"], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
  });
  if (run.status !== 0) {
    return { available: false, changedPaths: [] };
  }
  const changedPaths = (run.stdout ?? "")
    .split(/\r?\n/u)
    .filter((line) => line.trim().length > 0)
    .map((line) => line.slice(3).trim())
    .map((candidate) => {
      const renameParts = candidate.split(" -> ");
      return renameParts.length > 1 ? renameParts[renameParts.length - 1] : candidate;
    })
    .map((candidate) => {
      if (!candidate.startsWith("\"") || !candidate.endsWith("\"")) return candidate;
      try {
        return /** @type {string} */ (JSON.parse(candidate));
      } catch {
        return candidate.slice(1, -1);
      }
    })
    .map((candidate) => candidate.replace(/\\/g, "/"));
  return { available: true, changedPaths };
}

/**
 * @param {string[]} changedPaths
 * @returns {string[]}
 */
export function filterNonBootstrapChangedPaths(changedPaths) {
  return changedPaths.filter((candidate) => {
    if (BOOTSTRAP_OWNED_FILES.has(candidate)) return false;
    return !BOOTSTRAP_OWNED_PREFIXES.some((prefix) => candidate === prefix.slice(0, -1) || candidate.startsWith(prefix));
  });
}

/**
 * @param {string} candidate
 * @returns {boolean}
 */
export function isTransientBackupPath(candidate) {
  const basename = path.posix.basename(candidate.replace(/\\/g, "/")).toLowerCase();
  return basename.startsWith(".#") || /(?:~|\.bak|\.backup|\.orig|\.rej|\.tmp|\.swp|\.swo|\.old)$/u.test(basename);
}

/**
 * @param {string} projectRoot
 * @param {string} candidate
 * @returns {boolean}
 */
export function isDiagnosticSideEffectPath(projectRoot, candidate) {
  const normalized = candidate.replace(/\\/g, "/").replace(/^\.\//u, "");
  if (!normalized || path.posix.isAbsolute(normalized) || normalized.startsWith("../")) {
    return false;
  }
  const resolved = path.resolve(projectRoot, normalized);
  const relative = path.relative(projectRoot, resolved).replace(/\\/g, "/");
  if (relative.startsWith("../") || relative === "" || relative !== normalized) {
    return false;
  }
  let stat;
  try {
    stat = fs.statSync(resolved);
  } catch {
    return false;
  }
  if (!stat.isFile() || stat.size > 4096) {
    return false;
  }
  let content;
  try {
    content = fs.readFileSync(resolved, "utf8");
  } catch {
    return false;
  }
  return DIAGNOSTIC_SIDE_EFFECT_SIGNATURES.some((signature) => content.startsWith(signature));
}

/**
 * @param {string[]} changedPaths
 * @param {string} projectRoot
 * @returns {string[]}
 */
export function filterDiagnosticSideEffectPaths(changedPaths, projectRoot) {
  return changedPaths.filter((candidate) => isDiagnosticSideEffectPath(projectRoot, candidate));
}

/**
 * @param {string} candidate
 * @returns {boolean}
 */
export function isRunnerOwnedStatePath(candidate) {
  const normalized = candidate.replace(/\\/g, "/").replace(/^\.\//u, "");
  return RUNNER_OWNED_STATE_PREFIXES.some(
    (prefix) => normalized === prefix.slice(0, -1) || normalized.startsWith(prefix),
  );
}

/**
 * @param {string[]} changedPaths
 * @returns {string[]}
 */
export function filterRunnerOwnedStatePaths(changedPaths) {
  return changedPaths.filter((candidate) => isRunnerOwnedStatePath(candidate));
}

/**
 * @param {string} projectRoot
 * @param {string | null} filePath
 * @returns {string | null}
 */
function resolveProjectRelativeFile(projectRoot, filePath) {
  if (!filePath) return null;
  const resolved = path.isAbsolute(filePath) ? filePath : path.resolve(projectRoot, filePath);
  const relative = path.relative(projectRoot, resolved).replace(/\\/g, "/");
  return relative.startsWith("../") || relative === "" ? null : relative;
}

/**
 * @param {string} projectRoot
 * @param {string} artifactsRoot
 * @returns {{ ignoredInputFiles: string[], allowedPaths: string[], forbiddenPaths: string[] }}
 */
export function loadMissionScope(projectRoot, artifactsRoot) {
  const packetFiles = listJsonFiles(artifactsRoot).filter((filePath) => path.basename(filePath).includes(".artifact."));
  for (const packetFile of packetFiles) {
    const packet = readJsonFile(packetFile);
    if (asString(packet?.packet_type) !== "intake-request") continue;
    const bodyRef = asString(packet?.body_ref);
    if (!bodyRef || !fs.existsSync(bodyRef)) continue;
    const body = readJsonFile(bodyRef);
    const featureRequest = asRecord(body?.feature_request);
    const requestFile = resolveProjectRelativeFile(projectRoot, asString(featureRequest.request_file));
    return {
      ignoredInputFiles: requestFile ? [requestFile] : [],
      allowedPaths: [],
      forbiddenPaths: [],
    };
  }
  return { ignoredInputFiles: [], allowedPaths: [], forbiddenPaths: [] };
}

/**
 * @param {string[]} changedPaths
 * @param {{ ignoredInputFiles: string[], allowedPaths: string[], forbiddenPaths: string[] }} missionScope
 * @param {{ projectRoot?: string | null }} [options]
 */
export function resolveMissionScopedChanges(changedPaths, missionScope, options = {}) {
  const ignoredInputFiles = new Set(missionScope.ignoredInputFiles);
  const projectRoot = asString(options.projectRoot);
  const diagnosticSideEffectPaths = projectRoot ? filterDiagnosticSideEffectPaths(changedPaths, projectRoot) : [];
  const diagnosticSideEffects = new Set(diagnosticSideEffectPaths);
  const scopeCandidates = changedPaths.filter(
    (changedPath) =>
      !ignoredInputFiles.has(changedPath) &&
      !isTransientBackupPath(changedPath) &&
      !diagnosticSideEffects.has(changedPath),
  );
  return {
    ignoredInputFiles: missionScope.ignoredInputFiles,
    diagnosticSideEffectPaths,
    nonInputChangedPaths: scopeCandidates,
    meaningfulChangedPaths: scopeCandidates,
  };
}

/**
 * @param {{
 *   projectRoot: string,
 *   artifactsRoot: string,
 *   evidenceRoot?: string | null,
 * }} options
 * @returns {{
 *   gitStatusAvailable: boolean,
 *   gitStatusRoot: string,
 *   changedPaths: string[],
 *   nonBootstrapChangedPaths: string[],
 *   nonInputChangedPaths: string[],
 *   meaningfulChangedPaths: string[],
 *   runnerOwnedStatePaths: string[],
 *   ignoredInputFiles: string[],
 *   diagnosticSideEffectPaths: string[],
 * }}
 */
export function collectMissionChangeEvidence(options) {
  const gitStatusRoot = asString(options.evidenceRoot) ?? options.projectRoot;
  const changedPathStatus = listChangedPaths(gitStatusRoot);
  const nonBootstrapChangedPaths = filterNonBootstrapChangedPaths(changedPathStatus.changedPaths);
  const runnerOwnedStatePaths = filterRunnerOwnedStatePaths(changedPathStatus.changedPaths);
  const missionScope = loadMissionScope(gitStatusRoot, options.artifactsRoot);
  const missionScopedChanges = resolveMissionScopedChanges(nonBootstrapChangedPaths, missionScope, {
    projectRoot: gitStatusRoot,
  });
  return {
    gitStatusAvailable: changedPathStatus.available,
    gitStatusRoot,
    changedPaths: changedPathStatus.changedPaths,
    nonBootstrapChangedPaths,
    nonInputChangedPaths: missionScopedChanges.nonInputChangedPaths,
    meaningfulChangedPaths: missionScopedChanges.meaningfulChangedPaths,
    runnerOwnedStatePaths,
    ignoredInputFiles: missionScopedChanges.ignoredInputFiles,
    diagnosticSideEffectPaths: missionScopedChanges.diagnosticSideEffectPaths,
  };
}
