import { QUALIFICATION_CELL_CONTRACT_FAMILIES, QUALIFICATION_CELL_EXAMPLE_RULES } from "./qualification-cell-contract-family.mjs";

export const LIVE_E2E_OBSERVATION_STATUS_VALUES = [
  "pass",
  "warn",
  "not_pass",
  "blocked",
  "interaction_required",
  "resumed",
];
const LIVE_E2E_RUN_HEALTH_STATUS_VALUES = ["pass", "warn", "fail", "blocked"];
const LIVE_E2E_QUALITY_ASSESSMENT_STATUS_VALUES = ["pass", "warn", "fail", "not_evaluated"];
const LIVE_E2E_SCENARIO_VALUES = ["regress", "release", "repair", "governance"];
const LIVE_E2E_PROVIDER_VARIANT_VALUES = ["openai-primary", "anthropic-primary", "open-code-primary", "qwen-primary"];
export const EXTERNAL_REFERENCE_PREFIXES = [
  "evidence://",
  "schema://",
  "approval://",
  "incident://",
  "review://",
  "redact://",
  "validate.",
  "retry.",
  "repair.",
];

/** @type {ReadonlyArray<import("./index.d.ts").ContractFamilyIndexEntry>} */
export const PRIVATE_CONTRACT_FAMILY_INDEX = Object.freeze([
  {
    family: "live-e2e-observation-report",
    familyGroup: "execution-and-quality",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-observation-report.md",
    exampleGlob: "scripts/live-e2e/fixtures/contracts/live-e2e-observation-report*.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "run_id",
      "profile_id",
      "report_status",
      "operator_context",
      "controller_state_ref",
      "flow_range",
      "flow_range_policy",
      "overall_status",
      "aor_installation",
      "aor_installation_proof_file",
      "setup_journal",
      "step_journal",
      "final_analysis",
      "interactive_decisions",
      "frontend_interactions",
      "evidence_refs",
    ],
    fieldTypes: {
      report_id: "string",
      run_id: "string",
      profile_id: "string",
      report_status: "string",
      operator_context: "object",
      controller_state_ref: "string",
      flow_range: "object",
      flow_range_policy: "string",
      overall_status: "string",
      aor_installation: "object",
      aor_installation_proof_file: "string",
      setup_journal: "array",
      step_journal: "array",
      final_analysis: "object",
      interactive_decisions: "array",
      frontend_interactions: "array",
      evidence_refs: "array",
    },
    forbiddenFields: [
      "step_matrix",
      "verdict_matrix",
      "artifact_quality_matrix",
      "code_quality_after_delivery",
      "continuation_decisions",
      "quality_judgement",
      "runner_quality_summary",
      "final_skill_agent_verdict_request_file",
      "final_skill_agent_verdict_file",
      "final_skill_agent_verdict",
      "agent_artifact_review_request_file",
      "canonical_status",
      "artifact_quality_status",
      "delivery_status",
      "coverage_status",
      "acceptance_status",
    ],
    enumChecks: [
      { field: "overall_status", allowedValues: LIVE_E2E_OBSERVATION_STATUS_VALUES },
      { field: "report_status", allowedValues: ["final", "in_progress"] },
      { field: "flow_range_policy", allowedValues: ["delivery_default", "full_lifecycle"] },
    ],
  },
  {
    family: "live-e2e-run-health-report",
    familyGroup: "execution-and-quality",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-run-health-report.md",
    exampleGlob: "scripts/live-e2e/fixtures/contracts/live-e2e-run-health-report*.yaml",
    status: "implemented",
    requiredFields: [
      "report_id",
      "run_id",
      "profile_id",
      "generated_at",
      "source_run_summary_file",
      "source_observation_report_file",
      "overall_status",
      "lifecycle_completion",
      "command_health",
      "controller_health",
      "provider_health",
      "target_environment_health",
      "diagnostic_health",
      "evidence_health",
      "failure_summary",
      "resume_interaction_health",
      "run_findings",
      "evidence_refs",
    ],
    fieldTypes: {
      report_id: "string",
      run_id: "string",
      profile_id: "string",
      generated_at: "string",
      source_run_summary_file: "string",
      source_observation_report_file: "string",
      overall_status: "string",
      lifecycle_completion: "object",
      command_health: "object",
      controller_health: "object",
      provider_health: "object",
      target_environment_health: "object",
      diagnostic_health: "object",
      evidence_health: "object",
      failure_summary: "object",
      resume_interaction_health: "object",
      run_findings: "array",
      evidence_refs: "array",
    },
    forbiddenFields: [
      "quality_judgement",
      "runner_quality_summary",
      "final_skill_agent_verdict",
      "target_code_correctness",
      "target_ui_ux_quality",
      "ui_ux_quality",
      "accessibility_quality",
      "aor_operator_ui_ux_quality",
      "aor_operator_accessibility_quality",
      "artifact_content_quality",
    ],
    enumChecks: [{ field: "overall_status", allowedValues: LIVE_E2E_RUN_HEALTH_STATUS_VALUES }],
  },
  {
    family: "live-e2e-quality-assessment-report",
    familyGroup: "execution-and-quality",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-quality-assessment-report.md",
    exampleGlob: "scripts/live-e2e/fixtures/contracts/live-e2e-quality-assessment-report*.yaml",
    status: "implemented",
    requiredFields: [
      "assessment_id",
      "run_id",
      "profile_id",
      "generated_at",
      "evaluator",
      "source_run_summary_file",
      "source_observation_report_file",
      "source_run_health_report_file",
      "overall_status",
      "dimensions",
      "gap_report",
      "findings",
      "recommended_followups",
      "evidence_refs",
    ],
    fieldTypes: {
      assessment_id: "string",
      run_id: "string",
      profile_id: "string",
      generated_at: "string",
      evaluator: "object",
      source_run_summary_file: "string",
      source_observation_report_file: "string",
      source_run_health_report_file: "string",
      assessment_request_file: "string",
      overall_status: "string",
      dimensions: "object",
      gap_report: "object",
      findings: "array",
      recommended_followups: "array",
      evidence_refs: "array",
    },
    forbiddenFields: [
      "quality_judgement",
      "runner_quality_summary",
      "final_skill_agent_verdict",
      "canonical_status",
      "acceptance_status",
      "coverage_status",
      "ui_ux_quality",
      "accessibility_quality",
      "target_ui_ux_quality",
    ],
    enumChecks: [{ field: "overall_status", allowedValues: LIVE_E2E_QUALITY_ASSESSMENT_STATUS_VALUES }],
  },
  ...QUALIFICATION_CELL_CONTRACT_FAMILIES,
  {
    family: "live-e2e-step-quality-assessment-request",
    familyGroup: "execution-and-quality",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-step-quality-assessment-request.md",
    exampleGlob: "scripts/live-e2e/fixtures/contracts/live-e2e-step-quality-assessment-request*.yaml",
    status: "implemented",
    requiredFields: [
      "request_id",
      "run_id",
      "profile_id",
      "generated_at",
      "evaluator",
      "target_catalog_id",
      "feature_mission_id",
      "feature_size",
      "mission_class",
      "step_id",
      "step_name",
      "step_iteration",
      "source_agent_decision_request_file",
      "source_operator_decision_file",
      "requested_assessment_method",
      "rubric_version",
      "rubric",
      "evaluator_input_refs",
      "expected_assessment_report_file",
      "evidence_refs",
    ],
    fieldTypes: {
      request_id: "string",
      run_id: "string",
      profile_id: "string",
      generated_at: "string",
      evaluator: "object",
      target_catalog_id: "string",
      feature_mission_id: "string",
      feature_size: "string",
      mission_class: "string",
      step_id: "string",
      step_name: "string",
      step_iteration: "number",
      source_agent_decision_request_file: "string",
      source_operator_decision_file: "string",
      requested_assessment_method: "string",
      rubric_version: "string",
      rubric: "object",
      evaluator_input_refs: "array",
      expected_assessment_report_file: "string",
      evidence_refs: "array",
    },
    enumChecks: [],
  },
  {
    family: "live-e2e-step-quality-assessment-report",
    familyGroup: "execution-and-quality",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-step-quality-assessment-report.md",
    exampleGlob: "scripts/live-e2e/fixtures/contracts/live-e2e-step-quality-assessment-report*.yaml",
    status: "implemented",
    requiredFields: [
      "assessment_id",
      "run_id",
      "profile_id",
      "generated_at",
      "evaluator",
      "target_catalog_id",
      "feature_mission_id",
      "feature_size",
      "mission_class",
      "step_id",
      "step_name",
      "step_iteration",
      "source_agent_decision_request_file",
      "source_operator_decision_file",
      "source_assessment_request_file",
      "assessment_method",
      "rubric_version",
      "evaluator_input_refs",
      "evaluator_output_ref",
      "status",
      "decision",
      "dimensions",
      "findings",
      "repair_instructions",
      "inspected_evidence_refs",
      "evidence_refs",
    ],
    fieldTypes: {
      assessment_id: "string",
      run_id: "string",
      profile_id: "string",
      generated_at: "string",
      evaluator: "object",
      target_catalog_id: "string",
      feature_mission_id: "string",
      feature_size: "string",
      mission_class: "string",
      step_id: "string",
      step_name: "string",
      step_iteration: "number",
      source_agent_decision_request_file: "string",
      source_operator_decision_file: "string",
      source_assessment_request_file: "string",
      assessment_method: "string",
      rubric_version: "string",
      evaluator_input_refs: "array",
      evaluator_output_ref: "string",
      status: "string",
      decision: "string",
      dimensions: "object",
      findings: "array",
      repair_instructions: "array",
      inspected_evidence_refs: "array",
      evidence_refs: "array",
    },
    enumChecks: [],
  },
  {
    family: "live-e2e-provider-variant",
    familyGroup: "operations",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-provider-variant.md",
    exampleGlob: "scripts/live-e2e/catalog/providers/*.yaml",
    status: "implemented",
    requiredFields: [
      "provider_variant_id",
      "provider",
      "primary_adapter",
      "fallback_policy",
      "route_override_policy",
    ],
    fieldTypes: {
      provider_variant_id: "string",
      provider: "string",
      primary_adapter: "string",
      fallback_policy: "object",
      route_override_policy: "object",
    },
    enumChecks: [{ field: "provider_variant_id", allowedValues: LIVE_E2E_PROVIDER_VARIANT_VALUES }],
  },
  {
    family: "live-e2e-scenario-policy",
    familyGroup: "operations",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-scenario-policy.md",
    exampleGlob: "scripts/live-e2e/catalog/scenarios/*.yaml",
    status: "implemented",
    requiredFields: [
      "scenario_family",
      "required_stages",
      "required_evidence",
      "delivery_mode_policy",
      "release_required",
      "incident_policy",
      "governance_policy",
    ],
    fieldTypes: {
      scenario_family: "string",
      required_stages: "array",
      required_evidence: "array",
      delivery_mode_policy: "string",
      release_required: "boolean",
      incident_policy: "object",
      governance_policy: "object",
    },
    enumChecks: [{ field: "scenario_family", allowedValues: LIVE_E2E_SCENARIO_VALUES }],
  },
  {
    family: "live-e2e-target-catalog",
    familyGroup: "operations",
    sourceContract: "scripts/live-e2e/docs/contracts/live-e2e-target-catalog.md",
    exampleGlob: "scripts/live-e2e/catalog/targets/*.yaml",
    status: "implemented",
    requiredFields: [
      "catalog_id",
      "repo",
      "verification",
      "safety_defaults",
      "required_matrix_cells",
      "provider_comparison_pairs",
      "feature_missions",
    ],
    fieldTypes: {
      catalog_id: "string",
      repo: "object",
      verification: "object",
      safety_defaults: "object",
      required_matrix_cells: "array",
      manual_matrix_cells: "array",
      provider_comparison_pairs: "array",
      feature_missions: "array",
    },
    enumChecks: [],
  },
]);

export const PRIVATE_EXAMPLE_FAMILY_RESOLUTION_RULES = Object.freeze([
  {
    regex: /^scripts\/live-e2e\/fixtures\/contracts\/live-e2e-observation-report[^/]*\.ya?ml$/,
    family: "live-e2e-observation-report",
  },
  {
    regex: /^scripts\/live-e2e\/fixtures\/contracts\/live-e2e-run-health-report[^/]*\.ya?ml$/,
    family: "live-e2e-run-health-report",
  },
  {
    regex: /^scripts\/live-e2e\/fixtures\/contracts\/live-e2e-quality-assessment-report[^/]*\.ya?ml$/,
    family: "live-e2e-quality-assessment-report",
  },
  ...QUALIFICATION_CELL_EXAMPLE_RULES,
  {
    regex: /^scripts\/live-e2e\/fixtures\/contracts\/live-e2e-step-quality-assessment-request[^/]*\.ya?ml$/,
    family: "live-e2e-step-quality-assessment-request",
  },
  {
    regex: /^scripts\/live-e2e\/fixtures\/contracts\/live-e2e-step-quality-assessment-report[^/]*\.ya?ml$/,
    family: "live-e2e-step-quality-assessment-report",
  },
]);
