export const RUNTIME_ROOT_DIRNAME = ".aor";

const COMMAND_DEFINITIONS = Object.freeze([
  {
    command: "project init",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Discover project root, load profile, and initialize runtime-root layout.",
    inputs: [
      "--project-ref <path> (optional, defaults to cwd discovery)",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "project_profile_ref",
      "runtime_layout",
      "runtime_state_file",
      "artifact_packet_id",
      "artifact_packet_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: [],
    contractFamilies: ["project-profile"],
  },
  {
    command: "project analyze",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Analyze repository facts and write durable project-analysis report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--route-overrides <step=route_id,...> (optional)",
      "--policy-overrides <step=policy_id,...> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "analysis_report_id",
      "analysis_report_file",
      "route_resolution_file",
      "route_resolution_steps",
      "asset_resolution_file",
      "asset_resolution_steps",
      "policy_resolution_file",
      "policy_resolution_steps",
      "evaluation_registry_file",
      "evaluation_registry_suites",
      "evaluation_registry_datasets",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["project-analysis-report"],
  },
  {
    command: "project validate",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Run deterministic validation checks and persist validation-report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--require-approved-handoff (optional)",
      "--handoff-packet <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "validation_report_id",
      "validation_report_file",
      "validation_status",
      "validation_blocking",
      "handoff_gate_enforced",
      "handoff_gate_status",
      "handoff_gate_blocking",
      "handoff_packet_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["validation-report"],
  },
  {
    command: "project verify",
    category: "project-bootstrap",
    status: "implemented",
    summary: "Validate command contract inputs for bounded verify preflight flow.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--require-validation-pass (optional)",
      "--routed-dry-run-step <step_class> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "validation_gate_enforced",
      "validation_gate_status",
      "verify_summary_file",
      "step_result_files",
      "routed_step_result_id",
      "routed_step_result_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["step-result"],
  },
  {
    command: "eval run",
    category: "quality-workflows",
    status: "implemented",
    summary: "Run an offline evaluation suite and persist a durable evaluation-report.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--suite-ref <suite_id@vN> (optional, defaults to project eval policy)",
      "--subject-ref <subject_type://target>",
      "--subject-version <version> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "evaluation_report_id",
      "evaluation_report_file",
      "evaluation_status",
      "evaluation_blocking",
      "evaluation_suite_ref",
      "evaluation_subject_ref",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "subject-ref"],
    contractFamilies: ["evaluation-report"],
  },
  {
    command: "harness certify",
    category: "quality-workflows",
    status: "implemented",
    summary: "Certify a changed asset set from eval and harness replay evidence.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--asset-ref <asset://target>",
      "--subject-ref <subject_type://target>",
      "--suite-ref <suite_id@vN> (optional)",
      "--step-class <step_class> (optional, defaults to implement)",
      "--from-channel <channel> (optional, defaults to candidate)",
      "--to-channel <channel> (optional, defaults to stable)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "promotion_decision_id",
      "promotion_decision_file",
      "promotion_decision_status",
      "certification_evaluation_report_file",
      "certification_harness_capture_file",
      "certification_harness_replay_file",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "asset-ref", "subject-ref"],
    contractFamilies: ["promotion-decision"],
  },
  {
    command: "handoff prepare",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Materialize wave-ticket and pending handoff-packet from approved bootstrap artifact.",
    inputs: [
      "--project-ref <path>",
      "--project-profile <path> (optional)",
      "--runtime-root <path> (optional)",
      "--ticket-id <id> (optional)",
      "--approved-artifact <path> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "wave_ticket_id",
      "wave_ticket_file",
      "handoff_packet_id",
      "handoff_packet_file",
      "handoff_status",
      "handoff_approval_state",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["wave-ticket", "handoff-packet"],
  },
  {
    command: "handoff approve",
    category: "intake-and-planning",
    status: "implemented",
    summary: "Approve handoff-packet with explicit approval reference for execution gating.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--handoff-packet <path> (optional)",
      "--approval-ref <ref>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "handoff_packet_id",
      "handoff_packet_file",
      "handoff_status",
      "handoff_approval_state",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "approval-ref"],
    contractFamilies: ["handoff-packet"],
  },
  { command: "intake create", category: "intake-and-planning", status: "planned" },
  { command: "discovery run", category: "intake-and-planning", status: "planned" },
  { command: "spec build", category: "intake-and-planning", status: "planned" },
  { command: "wave create", category: "intake-and-planning", status: "planned" },
  { command: "run start", category: "execution-lifecycle", status: "planned" },
  { command: "run pause", category: "execution-lifecycle", status: "planned" },
  { command: "run resume", category: "execution-lifecycle", status: "planned" },
  { command: "run steer", category: "execution-lifecycle", status: "planned" },
  { command: "run cancel", category: "execution-lifecycle", status: "planned" },
  {
    command: "run status",
    category: "execution-lifecycle",
    status: "implemented",
    summary: "Inspect run summaries and optionally follow live events through the control-plane stream.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--follow <true|false> (optional)",
      "--after-event-id <event_id> (optional)",
      "--max-replay <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "run_summaries",
      "follow_mode",
      "stream_protocol",
      "stream_backpressure",
      "replay_events",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: ["live-run-event", "step-result", "delivery-manifest", "release-packet", "promotion-decision"],
  },
  { command: "harness replay", category: "quality-workflows", status: "planned" },
  { command: "asset promote", category: "quality-workflows", status: "planned" },
  { command: "asset freeze", category: "quality-workflows", status: "planned" },
  { command: "deliver prepare", category: "delivery-and-release", status: "planned" },
  { command: "release prepare", category: "delivery-and-release", status: "planned" },
  {
    command: "packet show",
    category: "delivery-and-release",
    status: "implemented",
    summary: "List packet artifacts from runtime storage through the shared API read surface.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--family <contract_family|all> (optional)",
      "--limit <number> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "packet_artifacts",
      "selected_family",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: [
      "artifact-packet",
      "wave-ticket",
      "handoff-packet",
      "delivery-plan",
      "delivery-manifest",
      "release-packet",
    ],
  },
  {
    command: "evidence show",
    category: "delivery-and-release",
    status: "implemented",
    summary: "Inspect step results, quality artifacts, and delivery evidence through one read-only command.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "step_results",
      "quality_artifacts",
      "delivery_manifests",
      "promotion_decisions",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref"],
    contractFamilies: [
      "step-result",
      "validation-report",
      "evaluation-report",
      "incident-report",
      "promotion-decision",
      "delivery-manifest",
      "release-packet",
    ],
  },
  { command: "incident open", category: "incidents-and-audit", status: "planned" },
  { command: "incident show", category: "incidents-and-audit", status: "planned" },
  { command: "audit runs", category: "incidents-and-audit", status: "planned" },
  {
    command: "live-e2e start",
    category: "live-e2e-and-ui",
    status: "implemented",
    summary:
      "Start one standard live E2E orchestration run from a catalog profile and emit durable summary/scorecard/learning-loop artifacts.",
    inputs: [
      "--project-ref <path>",
      "--profile <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id> (optional)",
      "--hold-open <true|false> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "live_e2e_profile_ref",
      "live_e2e_run_id",
      "live_e2e_run_status",
      "live_e2e_run_summary_file",
      "live_e2e_scorecard_files",
      "live_e2e_abort_supported",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "profile"],
    contractFamilies: [
      "live-e2e-profile",
      "live-run-event",
      "incident-report",
      "step-result",
      "evaluation-report",
      "delivery-manifest",
      "release-packet",
    ],
  },
  {
    command: "live-e2e status",
    category: "live-e2e-and-ui",
    status: "implemented",
    summary: "Observe one standard live E2E run and optionally issue a bounded abort request.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--abort <true|false> (optional)",
      "--reason <text> (optional)",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "live_e2e_run_id",
      "live_e2e_run_status",
      "live_e2e_run_summary_file",
      "live_e2e_scorecards",
      "live_e2e_abort_applied",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: [
      "live-run-event",
      "incident-report",
      "step-result",
      "evaluation-report",
      "delivery-manifest",
      "release-packet",
    ],
  },
  {
    command: "live-e2e report",
    category: "live-e2e-and-ui",
    status: "implemented",
    summary: "Read run summary and per-target scorecards for one standard live E2E run.",
    inputs: [
      "--project-ref <path>",
      "--runtime-root <path> (optional)",
      "--run-id <id>",
      "--help",
    ],
    outputs: [
      "resolved_project_ref",
      "resolved_runtime_root",
      "live_e2e_run_id",
      "live_e2e_run_status",
      "live_e2e_run_summary_file",
      "live_e2e_scorecards",
      "read_only",
      "future_control_hooks",
      "contract_families",
      "command_catalog_alignment",
    ],
    requiredFlags: ["project-ref", "run-id"],
    contractFamilies: ["incident-report", "step-result", "evaluation-report", "delivery-manifest", "release-packet"],
  },
  { command: "ui attach", category: "live-e2e-and-ui", status: "planned" },
  { command: "ui detach", category: "live-e2e-and-ui", status: "planned" },
]);

export function getCliCommandCatalog() {
  return COMMAND_DEFINITIONS.map((definition) => ({ ...definition }));
}

export function getImplementedCommands() {
  return getCliCommandCatalog().filter((definition) => definition.status === "implemented");
}

export function getPlannedCommands() {
  return getCliCommandCatalog().filter((definition) => definition.status === "planned");
}

export function getCommandDefinition(command) {
  return getCliCommandCatalog().find((definition) => definition.command === command) ?? null;
}
